// RedTeamSimmer - Only supports Winodws agents or now. Some of the Linux/Mac is still here. That needs to be removed from here and added to an OS specific agent.
// https;//github.com/BreachSimRange/RedTeamSimmer
// Abx
package main

import (
	"archive/zip"
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"syscall"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	ServerURL              = "http://192.168.46.138:5000"
	AdminToken             = "ChangeThisAdminToken!"
	AtomicsDir             = "./atomics"
	PollInterval           = 7 * time.Second
	FiledropPoll           = 5 * time.Second
	InvokeAtomicModuleDir  = "./Invoke-AtomicRedTeam"
	InvokeAtomicModuleZip  = "Invoke-AtomicRedTeam.zip"
	InvokeAtomicModulePsd1 = "Invoke-AtomicRedTeam.psd1"
	InvokeAtomicModuleUrl  = ServerURL + "/modules/" + InvokeAtomicModuleZip
	ConfigFile             = "./agent_config.json"

	// MITRE ATT&CK version this agent targets. v19 (April 2026) split the
	// Defense Evasion tactic into Stealth (TA0005) and Defense Impairment (TA0112).
	MitreVersion = "19.1"

	// Additional PowerShell modules (offline - hosted on YOUR server)
	PowershellYamlZip       = "powershell-yaml.zip"
	PowershellYamlPsd1      = "powershell-yaml.psd1"
	PowershellYamlUrl       = ServerURL + "/modules/" + PowershellYamlZip
	
	AtomicTestHarnessesZip  = "AtomicTestHarnesses.zip"
	AtomicTestHarnessesPsd1 = "AtomicTestHarnesses.psd1"
	AtomicTestHarnessesUrl  = ServerURL + "/modules/" + AtomicTestHarnessesZip
)

var AgentID string
var processedZips = make(map[string]bool)
var agentConfig AgentConfig
var invokeAtomicAvailable = false
var logMutex sync.Mutex

// TestExecutionResult stores detailed output from each test execution
type TestExecutionResult struct {
	TechniqueID     string
	TestNumber      string
	TestName        string
	Status          string
	PrereqOutput    []CommandOutput
	MainOutput      CommandOutput
	CleanupOutput   CommandOutput
	ErrorMessages   []string
	StartTime       time.Time
	EndTime         time.Time
	Duration        time.Duration
}

// CommandOutput stores output from a single command execution
type CommandOutput struct {
	Command       string
	StdoutLines   []string
	StderrLines   []string
	ExitCode      int
	ExecutionTime time.Duration
}

type AgentConfig struct {
	Startup       bool   `json:"startup"`
	JitterTime    int    `json:"jitter_time"`
	AgentInfo     string `json:"agent_info"`
	InstalledAV   string `json:"installed_av"`
	SecurityLevel string `json:"security_level"`
}

// AtomicTest represents a single test in the atomic YAML file
type AtomicTest struct {
	Name                   string                 `yaml:"name"`
	AutoGeneratedGuid      string                 `yaml:"auto_generated_guid"`
	Description            string                 `yaml:"description"`
	SupportedPlatforms     []string               `yaml:"supported_platforms"`
	InputArguments         map[string]InputArg    `yaml:"input_arguments"`
	DependencyExecutorName interface{}            `yaml:"dependency_executor_name"`
	Dependencies           []Dependency           `yaml:"dependencies"`
	Executor               Executor               `yaml:"executor"`
}

type InputArg struct {
	Description string      `yaml:"description"`
	Type        string      `yaml:"type"`
	Default     interface{} `yaml:"default"`
}

type Dependency struct {
	Description      string `yaml:"description"`
	PrereqCommand    string `yaml:"prereq_command"`
	GetPrereqCommand string `yaml:"get_prereq_command"`
}

type Executor struct {
	Name              string `yaml:"name"`
	ElevationRequired bool   `yaml:"elevation_required"`
	Command           string `yaml:"command"`
	CleanupCommand    string `yaml:"cleanup_command"`
}

type AtomicTechnique struct {
	AttackTechnique string       `yaml:"attack_technique"`
	DisplayName     string       `yaml:"display_name"`
	AtomicTests     []AtomicTest `yaml:"atomic_tests"`
}

func main() {
	// Change working directory to where the agent executable is located
	exePath, err := os.Executable()
	if err == nil {
		exeDir := filepath.Dir(exePath)
		os.Chdir(exeDir)
		fmt.Println("[*] Working directory set to:", exeDir)
	}

	AgentID = getHostname() + `\` + getUsername()
	fmt.Println("[*] Atomic Agent starting as:", AgentID)

	loadConfig()
	os.MkdirAll(AtomicsDir, 0755)
	absAtomicsPath, _ := filepath.Abs(AtomicsDir)
	externalPayloadsPath := filepath.Join(filepath.Dir(absAtomicsPath), "ExternalPayloads")
	if err := os.MkdirAll(externalPayloadsPath, 0755); err != nil {
		fmt.Println("[!] Failed to create ExternalPayloads folder:", err)
	} else {
		fmt.Println("[*] ExternalPayloads folder ready:", externalPayloadsPath)
	}
	register()
	
	// Ensure Invoke-AtomicRedTeam module is available
	ensureInvokeAtomicModule()

	go pollForTasks()
	go pollForFileDropConfirmations()

	for {
		time.Sleep(15 * time.Second)
	}
}

func loadConfig() {
	data, err := ioutil.ReadFile(ConfigFile)
	if err != nil {
		agentConfig = AgentConfig{
			Startup:       false,
			JitterTime:    5,
			AgentInfo:     "Default Agent",
			InstalledAV:   detectAV(),
			SecurityLevel: "Unknown",
		}
		saveConfig()
		return
	}
	json.Unmarshal(data, &agentConfig)
}

func saveConfig() {
	data, _ := json.MarshalIndent(agentConfig, "", "  ")
	ioutil.WriteFile(ConfigFile, data, 0644)
}

func getInstalledAV() string {
	// Map of process names to AV product names
	avProcessMap := map[string]string{
		// Windows Defender
		"msmpeng.exe":           "Windows Defender",
		"mpcmdrun.exe":          "Windows Defender",
		"securityhealthservice.exe": "Windows Security",
		"securityhealthhost.exe": "Windows Security",
		
		// CrowdStrike
		"csfalconservice.exe":   "CrowdStrike Falcon",
		"csfalconcontainer.exe": "CrowdStrike Falcon",
		"csagent.exe":           "CrowdStrike Falcon",
		
		// SentinelOne
		"sentinelagent.exe":     "SentinelOne",
		"sentinelctl.exe":       "SentinelOne",
		"sentinelservicehost.exe": "SentinelOne",
		
		// Carbon Black
		"cb.exe":                "VMware Carbon Black",
		"cbdefense.exe":         "Carbon Black Defense",
		"carbonblack.exe":       "VMware Carbon Black",
		"repmgr.exe":            "Carbon Black Response",
		
		// Symantec / Broadcom
		"ccsvchst.exe":          "Symantec Endpoint Protection",
		"sepmaster.exe":         "Symantec Endpoint Protection",
		"smc.exe":               "Symantec Endpoint Protection",
		"rtvscan.exe":           "Symantec Endpoint Protection",
		
		// McAfee
		"mcshield.exe":          "McAfee Endpoint Security",
		"mfetp.exe":             "McAfee Endpoint Security",
		"masvc.exe":             "McAfee Agent",
		"mfemms.exe":            "McAfee Endpoint Security",
		"mfemactl.exe":          "McAfee Endpoint Security",
		
		// Kaspersky
		"avp.exe":               "Kaspersky Endpoint Security",
		"avpui.exe":             "Kaspersky Endpoint Security",
		"kavfs.exe":             "Kaspersky Endpoint Security",
		"klnagent.exe":          "Kaspersky Security Center",
		
		// ESET
		"ekrn.exe":              "ESET Endpoint Security",
		"egui.exe":              "ESET Endpoint Security",
		"eguiproxy.exe":         "ESET Endpoint Security",
		
		// Trend Micro
		"coreserviceshell.exe":  "Trend Micro Apex One",
		"tmbmsrv.exe":           "Trend Micro",
		"ntrtscan.exe":          "Trend Micro OfficeScan",
		"tmccsf.exe":            "Trend Micro",
		"pccntmon.exe":          "Trend Micro",
		
		// Sophos
		"savservice.exe":        "Sophos Endpoint",
		"sophoshealth.exe":      "Sophos Endpoint",
		"sophosui.exe":          "Sophos Endpoint",
		"hmpalert.exe":          "Sophos Intercept X",
		"sophosfilescanner.exe": "Sophos Endpoint",
		
		// Bitdefender
		"bdagent.exe":           "Bitdefender Endpoint",
		"vsserv.exe":            "Bitdefender",
		"bdservicehost.exe":     "Bitdefender Endpoint",
		"epag.exe":              "Bitdefender GravityZone",
		
		// Cortex XDR (Palo Alto)
		"cyserver.exe":          "Cortex XDR",
		"traps.exe":             "Cortex XDR (Traps)",
		"cytray.exe":            "Cortex XDR",
		
		// Cylance
		"cylanceui.exe":         "Cylance PROTECT",
		"cylancesvc.exe":        "Cylance PROTECT",
		
		// Malwarebytes
		"mbam.exe":              "Malwarebytes",
		"mbamservice.exe":       "Malwarebytes",
		"mbamtray.exe":          "Malwarebytes",
		
		// Avast / AVG
		"avastui.exe":           "Avast Antivirus",
		"avastsvc.exe":          "Avast Antivirus",
		"avgui.exe":             "AVG Antivirus",
		"avgsvc.exe":            "AVG Antivirus",
		
		// F-Secure
		"fsgk32.exe":            "F-Secure",
		"fsav32.exe":            "F-Secure",
		"fsorsp.exe":            "F-Secure",
		
		// Webroot
		"wrsa.exe":              "Webroot SecureAnywhere",
		"wrsvc.exe":             "Webroot SecureAnywhere",
		
		// Cisco AMP
		"sfc.exe":               "Cisco Secure Endpoint (AMP)",
		"iptray.exe":            "Cisco Secure Endpoint (AMP)",
		
		// Microsoft Defender ATP / MDE
		"mssense.exe":           "Microsoft Defender for Endpoint",
		"sensecncproxy.exe":     "Microsoft Defender for Endpoint",
		
		// Elastic Security
		"elastic-agent.exe":     "Elastic Security",
		"elastic-endpoint.exe":  "Elastic Endpoint Security",
		
		// FireEye / Trellix
		"xagt.exe":              "Trellix Endpoint (FireEye)",
		"fireeye.exe":           "FireEye Endpoint",
	}

	var detectedAV []string
	seen := make(map[string]bool)

	if runtime.GOOS == "windows" {
		// Method 1: Check running processes
		cmd := exec.Command("tasklist", "/FO", "CSV", "/NH")
		output, err := cmd.Output()
		if err == nil {
			lines := strings.Split(string(output), "\n")
			for _, line := range lines {
				line = strings.ToLower(strings.TrimSpace(line))
				for procName, avName := range avProcessMap {
					if strings.Contains(line, strings.ToLower(procName)) {
						if !seen[avName] {
							detectedAV = append(detectedAV, avName)
							seen[avName] = true
						}
					}
				}
			}
		}

		// Method 2: Query WMI for AntiVirus products
		wmiCmd := exec.Command("powershell", "-Command", 
			"Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntiVirusProduct | Select-Object -ExpandProperty displayName")
		wmiOutput, err := wmiCmd.Output()
		if err == nil {
			wmiLines := strings.Split(string(wmiOutput), "\n")
			for _, line := range wmiLines {
				line = strings.TrimSpace(line)
				if line != "" && !seen[line] {
					detectedAV = append(detectedAV, line)
					seen[line] = true
				}
			}
		}

		// Method 3: Check Windows Security Center
		scCmd := exec.Command("powershell", "-Command",
			"Get-MpComputerStatus | Select-Object -Property AMServiceEnabled,AntispywareEnabled,AntivirusEnabled,RealTimeProtectionEnabled | ConvertTo-Json")
		scOutput, _ := scCmd.Output()
		if strings.Contains(string(scOutput), "true") {
			if !seen["Windows Defender"] {
				// Check if it's actually Windows Defender or third-party registered
				detectedAV = append(detectedAV, "Windows Defender (Active)")
				seen["Windows Defender"] = true
			}
		}

	} else {
		// Linux AV detection
		linuxAVMap := map[string]string{
			"clamd":           "ClamAV",
			"clamscan":        "ClamAV",
			"sophos":          "Sophos Antivirus for Linux",
			"savd":            "Sophos Antivirus for Linux",
			"cbagentd":        "Carbon Black",
			"falcon-sensor":   "CrowdStrike Falcon",
			"sentinelone":     "SentinelOne",
			"ds_agent":        "Trend Micro Deep Security",
			"bdserverd":       "Bitdefender",
		}

		cmd := exec.Command("ps", "aux")
		output, err := cmd.Output()
		if err == nil {
			outputStr := strings.ToLower(string(output))
			for procName, avName := range linuxAVMap {
				if strings.Contains(outputStr, procName) && !seen[avName] {
					detectedAV = append(detectedAV, avName)
					seen[avName] = true
				}
			}
		}
	}

	if len(detectedAV) == 0 {
		return "None Detected"
	}

	return strings.Join(detectedAV, ", ")
}

func detectAV() string {
	if runtime.GOOS != "windows" {
		return "N/A (Non-Windows)"
	}

	avList := []string{}
	knownAV := []string{
		"MsMpEng.exe",
		"AvastUI.exe",
		"avgui.exe",
		"ekrn.exe",
		"bdagent.exe",
	}

	for _, av := range knownAV {
		cmd := exec.Command("tasklist", "/FI", fmt.Sprintf("IMAGENAME eq %s", av))
		output, _ := cmd.Output()
		if strings.Contains(string(output), av) {
			avName := strings.TrimSuffix(av, ".exe")
			avList = append(avList, avName)
		}
	}

	if len(avList) == 0 {
		return "None Detected"
	}
	return strings.Join(avList, ", ")
}

func ensureInvokeAtomicModule() {
	// 1) Ensure Invoke-AtomicRedTeam exists
	_, err := findFileRecursive(InvokeAtomicModuleDir, "Invoke-AtomicRedTeam.psd1")
	if err != nil {
		fmt.Println("[*] Invoke-AtomicRedTeam module missing, downloading from server...")
		if err := downloadAndUnzip(InvokeAtomicModuleUrl, InvokeAtomicModuleDir); err != nil {
			fmt.Println("[!] Failed to download/unzip Invoke-AtomicRedTeam:", err)
			invokeAtomicAvailable = false
			return
		}
		// Verify it was extracted
		if _, err := findFileRecursive(InvokeAtomicModuleDir, "Invoke-AtomicRedTeam.psd1"); err != nil {
			fmt.Println("[!] Invoke-AtomicRedTeam PSD1 still not found after unzip")
			invokeAtomicAvailable = false
			return
		}
		fmt.Println("[*] Downloaded and unzipped Invoke-AtomicRedTeam")
	} else {
		fmt.Println("[*] Invoke-AtomicRedTeam module present.")
	}

	// 2) Ensure powershell-yaml exists (required dependency)
	_, err = findFileRecursive(InvokeAtomicModuleDir, PowershellYamlPsd1)
	if err != nil {
		fmt.Println("[*] powershell-yaml module missing, downloading from server...")
		if err := downloadAndUnzipNamed(PowershellYamlUrl, InvokeAtomicModuleDir, PowershellYamlZip); err != nil {
			fmt.Println("[!] Failed to download/unzip powershell-yaml:", err)
			fmt.Println("[!] Make sure powershell-yaml.zip is hosted at:", PowershellYamlUrl)
			invokeAtomicAvailable = false
			return
		}
		// Verify it was extracted
		if _, err := findFileRecursive(InvokeAtomicModuleDir, PowershellYamlPsd1); err != nil {
			fmt.Println("[!] powershell-yaml PSD1 still not found after unzip")
			invokeAtomicAvailable = false
			return
		}
		fmt.Println("[*] Downloaded and unzipped powershell-yaml")
	} else {
		fmt.Println("[*] powershell-yaml module present.")
	}

	// 3) Ensure AtomicTestHarnesses exists (needed for many tests)
	_, err = findFileRecursive(InvokeAtomicModuleDir, AtomicTestHarnessesPsd1)
	if err != nil {
		fmt.Println("[*] AtomicTestHarnesses module missing, downloading from server...")
		if err := downloadAndUnzipNamed(AtomicTestHarnessesUrl, InvokeAtomicModuleDir, AtomicTestHarnessesZip); err != nil {
			fmt.Println("[!] Failed to download/unzip AtomicTestHarnesses:", err)
			fmt.Println("[!] Make sure AtomicTestHarnesses.zip is hosted at:", AtomicTestHarnessesUrl)
			// Don't fail completely - some tests don't need this module
			fmt.Println("[!] Continuing without AtomicTestHarnesses (some tests may fail)")
		} else {
			// Verify it was extracted
			if _, err := findFileRecursive(InvokeAtomicModuleDir, AtomicTestHarnessesPsd1); err != nil {
				fmt.Println("[!] AtomicTestHarnesses PSD1 still not found after unzip")
				fmt.Println("[!] Continuing without AtomicTestHarnesses (some tests may fail)")
			} else {
				fmt.Println("[*] Downloaded and unzipped AtomicTestHarnesses")
			}
		}
	} else {
		fmt.Println("[*] AtomicTestHarnesses module present.")
	}

	// 4) Verify module can be imported
	invokeAtomicAvailable = testInvokeAtomicModule()
}

// downloadAndUnzipNamed downloads a ZIP and extracts it
func downloadAndUnzipNamed(url, destDir, tmpZipName string) error {
	fmt.Println("[*] Downloading:", url)
	
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return fmt.Errorf("download failed: HTTP %d for %s", resp.StatusCode, url)
	}

	if err := os.MkdirAll(destDir, 0755); err != nil {
		return err
	}

	tmp := filepath.Join(os.TempDir(), tmpZipName)
	out, err := os.Create(tmp)
	if err != nil {
		return err
	}

	written, err := io.Copy(out, resp.Body)
	out.Close()
	if err != nil {
		os.Remove(tmp)
		return err
	}
	
	fmt.Printf("[*] Downloaded %d bytes\n", written)
	defer os.Remove(tmp)

	return unzip(tmp, destDir)
}

func testInvokeAtomicModule() bool {
	if runtime.GOOS != "windows" {
		fmt.Println("[!] Invoke-AtomicRedTeam module test skipped (non-Windows).")
		return false
	}

	// Find the PSD1 files recursively (handles various ZIP layouts)
	iatPsd1, err := findFileRecursive(InvokeAtomicModuleDir, "Invoke-AtomicRedTeam.psd1")
	if err != nil {
		fmt.Println("[!] Invoke-AtomicRedTeam PSD1 not found:", err)
		return false
	}

	yamlPsd1, err := findFileRecursive(InvokeAtomicModuleDir, PowershellYamlPsd1)
	if err != nil {
		fmt.Println("[!] powershell-yaml PSD1 not found:", err)
		fmt.Println("[!] You need to host powershell-yaml.zip on your server at /modules/powershell-yaml.zip")
		return false
	}

	// AtomicTestHarnesses is optional but helpful
	harnessesPsd1, errHarness := findFileRecursive(InvokeAtomicModuleDir, AtomicTestHarnessesPsd1)
	harnessAvailable := errHarness == nil

	// Convert to absolute paths
	absYamlPsd1, _ := filepath.Abs(yamlPsd1)
	absIatPsd1, _ := filepath.Abs(iatPsd1)
	absHarnessPsd1 := ""
	if harnessAvailable {
		absHarnessPsd1, _ = filepath.Abs(harnessesPsd1)
		absHarnessPsd1 = strings.ReplaceAll(absHarnessPsd1, "\\", "/")
	}

	// Use forward slashes for PowerShell compatibility
	absYamlPsd1 = strings.ReplaceAll(absYamlPsd1, "\\", "/")
	absIatPsd1 = strings.ReplaceAll(absIatPsd1, "\\", "/")

	fmt.Println("[*] YAML module path:", absYamlPsd1)
	fmt.Println("[*] IAT module path:", absIatPsd1)
	if harnessAvailable {
		fmt.Println("[*] AtomicTestHarnesses path:", absHarnessPsd1)
	} else {
		fmt.Println("[*] AtomicTestHarnesses: Not available (some tests may fail)")
	}

	// Build import command for AtomicTestHarnesses (optional)
	harnessImport := ""
	if harnessAvailable {
		harnessImport = fmt.Sprintf(`
    # Import AtomicTestHarnesses (optional but helpful)
    try {
        Import-Module '%s' -Force -ErrorAction SilentlyContinue
        Write-Output "HARNESS_LOADED"
    } catch {
        Write-Output "HARNESS_SKIPPED"
    }
`, absHarnessPsd1)
	}

	// PowerShell test command - import all modules using file paths
	testCmd := fmt.Sprintf(`
$ErrorActionPreference = "Stop"
try {
    # Import powershell-yaml first (dependency)
    Import-Module '%s' -Force -ErrorAction Stop -Verbose:$false -WarningAction SilentlyContinue
    
    # Import Invoke-AtomicRedTeam
    Import-Module '%s' -Force -ErrorAction Stop -Verbose:$false -WarningAction SilentlyContinue
    %s
    # Verify Invoke-AtomicTest command exists
    if (Get-Command Invoke-AtomicTest -ErrorAction SilentlyContinue) {
        Write-Output "MODULE_AVAILABLE"
        exit 0
    } else {
        Write-Output "COMMAND_NOT_FOUND"
        exit 1
    }
} catch {
    Write-Output "IMPORT_ERROR: $($_.Exception.Message)"
    exit 1
}
`, absYamlPsd1, absIatPsd1, harnessImport)

	cmd := exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", testCmd)
	output, err := cmd.CombinedOutput()
	outputStr := string(output)

	fmt.Println("[*] Module test output:", outputStr)

	if err != nil {
		fmt.Println("[!] Invoke-AtomicRedTeam module test failed:", err)
		return false
	}

	if strings.Contains(outputStr, "MODULE_AVAILABLE") {
		fmt.Println("[*] Invoke-AtomicRedTeam module is functional")
		if strings.Contains(outputStr, "HARNESS_LOADED") {
			fmt.Println("[*] AtomicTestHarnesses module loaded successfully")
		}
		return true
	}

	fmt.Println("[!] Invoke-AtomicRedTeam module not functional")
	return false
}

// findFileRecursive searches for a file by name under a directory tree
func findFileRecursive(rootDir, fileName string) (string, error) {
	target := strings.ToLower(fileName)
	var found string

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return nil // Skip paths we can't access
		}
		if info == nil || info.IsDir() {
			return nil
		}
		if strings.ToLower(info.Name()) == target {
			found = path
			return io.EOF // Stop early
		}
		return nil
	})

	if err != nil && err != io.EOF {
		return "", err
	}
	if found == "" {
		return "", fmt.Errorf("%s not found under %s", fileName, rootDir)
	}
	return found, nil
}
// findYamlForTechnique locates the atomic YAML for a technique ID on the agent's disk.
//
// It tries a strict, ordered list of candidate paths. Notably, it does NOT
// perform a filesystem walk or fuzzy filename search - the previous behaviour
// of falling back to "any yaml whose filename matches" silently loaded the
// wrong file for sub-technique requests (e.g. T1071.001 would find and execute
// tests from T1071.yaml instead).
//
// For sub-technique requests like T1071.001, the resolver will fall back to the
// parent yaml (T1071/T1071.yaml) if no nested sub-tech folder exists. Callers
// should detect this fallback by checking atomicTech.AttackTechnique after
// loading the yaml. The server-side resolver picks the correct test index in
// that case, so the agent can trust the test_index it was given.
func findYamlForTechnique(tid string) (string, error) {
	absAtomicsPath, _ := filepath.Abs(AtomicsDir)
	baseTid := strings.Split(tid, ".")[0]
	isSubTech := strings.Contains(tid, ".")

	var possiblePaths []string
	if isSubTech {
		// Sub-technique: prefer nested sub-tech folder, then parent-holding-sub,
		// then parent yaml (which may contain the sub-tech tests embedded).
		possiblePaths = []string{
			filepath.Join(absAtomicsPath, tid, tid+".yaml"),
			filepath.Join(absAtomicsPath, baseTid, tid+".yaml"),
			filepath.Join(absAtomicsPath, baseTid, baseTid+".yaml"),
		}
	} else {
		// Parent technique: single canonical location.
		possiblePaths = []string{
			filepath.Join(absAtomicsPath, tid, tid+".yaml"),
		}
	}

	for _, path := range possiblePaths {
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}

	return "", fmt.Errorf("YAML not found for %s (tried: %s)", tid, strings.Join(possiblePaths, " | "))
}
func downloadAndUnzip(url, destDir string) error {
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	tmp := filepath.Join(os.TempDir(), InvokeAtomicModuleZip)
	out, err := os.Create(tmp)
	if err != nil {
		return err
	}

	_, err = io.Copy(out, resp.Body)
	out.Close()
	if err != nil {
		return err
	}
	defer os.Remove(tmp)

	return unzip(tmp, destDir)
}

func register() {
	info := map[string]interface{}{
		"hostname":       getHostname(),
		"username":       getUsername(),
		"os":             runtime.GOOS,
		"arch":           runtime.GOARCH,
		"startup":        agentConfig.Startup,
		"jitter_time":    agentConfig.JitterTime,
		"agent_info":     agentConfig.AgentInfo,
		"installed_av":   agentConfig.InstalledAV,
		"security_level": agentConfig.SecurityLevel,
		"mitre_version":  MitreVersion,
	}
	body := map[string]interface{}{
		"id":    AgentID,
		"token": AdminToken,
		"info":  info,
	}
	data, _ := json.Marshal(body)

	resp, err := http.Post(ServerURL+"/api/register", "application/json", bytes.NewReader(data))
	if err != nil {
		fmt.Println("[!] register() error:", err)
		return
	}
	defer resp.Body.Close()

	fmt.Println("[*] Registered with server as:", AgentID)
}

func getHostname() string {
	h, _ := os.Hostname()
	if h == "" {
		return "unknown"
	}
	return h
}

func getUsername() string {
	u := os.Getenv("USERNAME")
	if u == "" {
		u = os.Getenv("USER")
	}
	if u == "" {
		return "unknown"
	}
	return u
}

// PART 2: Polling, task handlers, filedrop, shutdown, config update


func pollForFileDropConfirmations() {
	for {
		files, err := ioutil.ReadDir(AtomicsDir)
		if err == nil {
			for _, f := range files {
				if strings.HasSuffix(f.Name(), ".zip") {
					full := filepath.Join(AtomicsDir, f.Name())

					if processedZips[f.Name()] {
						continue
					}

					fmt.Println("[*] Detected ZIP dropped by server:", f.Name())

					if err := unzip(full, AtomicsDir); err != nil {
						fmt.Println("[!] unzip failed:", err)
						processedZips[f.Name()] = true
						os.Remove(full)
						fmt.Println("[*] Removed corrupted ZIP:", f.Name())
						continue
					}

					os.Remove(full)
					fmt.Println("[*] Successfully extracted and removed ZIP:", f.Name())

					taskID := extractTaskIdFromZip(f.Name())
					if taskID != "" {
						fmt.Println("[*] Confirming file drop for task:", taskID)
						confirmFileDrop(taskID)
					}
				}
			}
		}
		time.Sleep(FiledropPoll)
	}
}

func confirmFileDrop(taskID string) {
	payload := map[string]interface{}{
		"agentId": AgentID,
		"taskId":  taskID,
	}
	data, _ := json.Marshal(payload)

	fmt.Println("[*] Sending confirmation for task:", taskID)

	req, err := http.NewRequest("POST", ServerURL+"/api/agent/confirm_file", bytes.NewReader(data))
	if err != nil {
		fmt.Println("[!] confirmFileDrop() request creation error:", err)
		return
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Println("[!] confirmFileDrop() HTTP error:", err)
		return
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	fmt.Println("[*] Confirmed extraction for task:", taskID, "| Server response:", string(body))
}

func extractTaskIdFromZip(zipname string) string {
	zipname = filepath.Base(zipname)
	if strings.Contains(zipname, "atomic_bundle_") {
		part := strings.Split(zipname, "atomic_bundle_")[1]
		part = strings.TrimSuffix(part, ".zip")
		return part
	}
	return ""
}

func downloadZip(fname string) (string, error) {
	url := ServerURL + "/uploads/" + AgentID + "/" + fname
	dest := filepath.Join(AtomicsDir, fname)

	fmt.Println("[*] Downloading ZIP from:", url)

	resp, err := http.Get(url)
	if err != nil {
		fmt.Println("[!] Download error:", err)
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		fmt.Printf("[!] Server returned status %d for URL: %s\n", resp.StatusCode, url)
		return "", fmt.Errorf("server returned status %d", resp.StatusCode)
	}

	fmt.Printf("[*] Response headers: Content-Type=%s, Content-Length=%s\n",
		resp.Header.Get("Content-Type"), resp.Header.Get("Content-Length"))

	out, err := os.Create(dest)
	if err != nil {
		fmt.Println("[!] Failed to create file:", err)
		return "", err
	}
	defer out.Close()

	written, err := io.Copy(out, resp.Body)
	if err != nil {
		fmt.Println("[!] Failed to copy data:", err)
		return "", err
	}

	fmt.Printf("[*] Saved ZIP: %s (%d bytes)\n", dest, written)

	if written < 100 {
		fmt.Printf("[!] WARNING: File too small (%d bytes), might be corrupted\n", written)
	}

	return dest, nil
}

func pollForTasks() {
	for {
		req, _ := http.NewRequest("GET", ServerURL+"/api/poll/"+AgentID, nil)
		req.Header.Set("X-AGENT-TOKEN", AdminToken)

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			fmt.Println("[!] Poll error:", err)
			time.Sleep(PollInterval)
			continue
		}

		var pkg struct {
			Status string                 `json:"status"`
			Task   map[string]interface{} `json:"task"`
		}

		json.NewDecoder(resp.Body).Decode(&pkg)
		resp.Body.Close()

		if pkg.Status == "task" && pkg.Task != nil {
			handleTask(pkg.Task)
		}

		time.Sleep(PollInterval)
	}
}

func handleTask(task map[string]interface{}) {
	taskID := toString(task["id"])
	taskType := toString(task["type"])

	fmt.Println("[*] Received task:", taskID, "| Type:", taskType)

	switch taskType {
	case "filedrop":
		handleFiledropTask(task, taskID)
	case "execute":
		handleExecuteTask(task, taskID)
	case "get_prereqs":
		handleGetPrereqsTask(task, taskID)
	case "shutdown":
		handleShutdownTask(taskID)
	case "update_config":
		handleUpdateConfig(task, taskID)
	default:
		fmt.Println("[!] Unknown task type:", taskType)
	}
}

// handleGetPrereqsTask downloads and installs all prerequisites for the selected tests
func handleGetPrereqsTask(task map[string]interface{}, taskID string) {
	techs, _ := task["techniques"].([]interface{})

	fmt.Println("[*] Getting prerequisites for task:", taskID)
	sendLiveLog(taskID, "[AGENT] ═══════════════════════════════════════════════════════════════", false)
	sendLiveLog(taskID, "[AGENT] GETTING PREREQUISITES", true)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] Processing %d technique(s)", len(techs)), true)
	sendLiveLog(taskID, "[AGENT] ═══════════════════════════════════════════════════════════════", false)

	allSuccess := true
	for idx, techInterface := range techs {
		tech, ok := techInterface.(map[string]interface{})
		if !ok {
			continue
		}

		tid := toString(tech["id"])
		testIndexStr := toString(tech["test_index"])
		testName := toString(tech["test_name"])
		if testName == "" {
			testName = toString(tech["name"])
		}
		expectedGuid := toString(tech["guid"])

		testIndex := 0
		fmt.Sscanf(testIndexStr, "%d", &testIndex)

		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, fmt.Sprintf("[PREREQ] (%d/%d) %s - Test #%d: %s", idx+1, len(techs), tid, testIndex, testName), true)

		success := getPrerequisitesForTest(tid, testIndex, expectedGuid, taskID)
		if !success {
			allSuccess = false
		}
	}

	sendLiveLog(taskID, "", false)
	sendLiveLog(taskID, "[AGENT] ═══════════════════════════════════════════════════════════════", false)
	if allSuccess {
		sendLiveLog(taskID, "[AGENT] All prerequisites installed successfully!", true)
	} else {
		sendLiveLog(taskID, "[AGENT] Some prerequisites could not be installed - check logs above", true)
	}
	sendLiveLog(taskID, "[AGENT] ═══════════════════════════════════════════════════════════════", false)

	status := "completed"
	if !allSuccess {
		status = "partial"
	}

	reportTask(map[string]interface{}{
		"task_id": taskID,
		"output":  "Prerequisites check completed",
		"status":  status,
	})
}


// CUSTOM PREREQUISITE HANDLER - Replaces Invoke-AtomicTest -GetPrereqs
// Directly parses YAML and executes prereq commands without spawning cmd.exe windows

func getPrerequisitesForTest(tid string, testIndex int, expectedGuid string, taskID string) bool {
	sendLiveLog(taskID, "[*] Using custom prerequisite handler...", false)

	// Find the YAML file
	yamlPath, err := findYamlForTechnique(tid)
	if err != nil {
		sendLiveLog(taskID, fmt.Sprintf("[ERROR] %v", err), false)
		return false
	}

	sendLiveLog(taskID, fmt.Sprintf("[*] Loading YAML: %s", yamlPath), false)

	// Load and parse YAML
	atomicTech, err := loadAtomicYaml(yamlPath)
	if err != nil {
		sendLiveLog(taskID, fmt.Sprintf("[ERROR] Failed to load YAML: %v", err), false)
		return false
	}

	if testIndex >= len(atomicTech.AtomicTests) {
		sendLiveLog(taskID, fmt.Sprintf("[ERROR] Test index %d out of range (max: %d)", testIndex, len(atomicTech.AtomicTests)-1), false)
		return false
	}

	test := atomicTech.AtomicTests[testIndex]

	// Safety net: if the server sent an expected GUID, verify it matches the
	// test we're about to run. A mismatch means the server resolved one test
	// but the agent's on-disk YAML has different content at that index (e.g.
	// atomics were updated on the server but not synced to the agent).
	if expectedGuid != "" && test.AutoGeneratedGuid != "" &&
		!strings.EqualFold(expectedGuid, test.AutoGeneratedGuid) {
		sendLiveLog(taskID, fmt.Sprintf(
			"[ERROR] GUID mismatch for %s test_index=%d: server expected %s, yaml has %s - refusing to run prereqs",
			tid, testIndex, expectedGuid, test.AutoGeneratedGuid), true)
		sendLiveLog(taskID, "[HINT] Agent atomics folder may be out of sync with server", false)
		return false
	}

	// Safety net: if we loaded a parent YAML for a sub-technique request
	// (e.g. asked for T1059.001 but loaded T1059.yaml because no nested
	// sub-tech folder existed), warn so operators can spot mismatches.
	// We still trust the server-provided test_index because the server-side
	// resolver is authoritative.
	if strings.Contains(tid, ".") && atomicTech.AttackTechnique != "" &&
		!strings.EqualFold(atomicTech.AttackTechnique, tid) {
		sendLiveLog(taskID, fmt.Sprintf("[INFO] Loaded parent YAML %s for sub-technique request %s (test_index=%d)",
			atomicTech.AttackTechnique, tid, testIndex), false)
	}

	// Skip tests that don't support this platform. The server should have
	// filtered these out already, but we double-check to avoid installing
	// Linux prerequisites on Windows hosts.
	if !isPlatformSupported(test.SupportedPlatforms) {
		sendLiveLog(taskID, fmt.Sprintf("[SKIP] %s test '%s' does not support %s (platforms=%v) - skipping prereqs",
			tid, test.Name, runtime.GOOS, test.SupportedPlatforms), false)
		return true // skipped != failed
	}

	// Manual tests have no executable prereq commands - nothing to install.
	if strings.EqualFold(test.Executor.Name, "manual") {
		sendLiveLog(taskID, fmt.Sprintf("[SKIP] %s test '%s' is manual - no prereqs to install", tid, test.Name), false)
		return true
	}

	sendLiveLog(taskID, fmt.Sprintf("[*] Test: %s", test.Name), false)
	sendLiveLog(taskID, fmt.Sprintf("[*] Executor: %s", test.Executor.Name), false)

	// Build input arguments with resolved paths
	absAtomicsPath, _ := filepath.Abs(AtomicsDir)
	absAtomicsPath = strings.ReplaceAll(absAtomicsPath, "\\", "/")

	// Create ExternalPayloads folder if needed
	externalPayloads := filepath.Join(filepath.Dir(absAtomicsPath), "ExternalPayloads")
	if err := os.MkdirAll(externalPayloads, 0755); err != nil {
		sendLiveLog(taskID, fmt.Sprintf("[WARNING] Could not create ExternalPayloads: %v", err), false)
	}

	finalArgs := make(map[string]string)
	finalArgs["PathToAtomicsFolder"] = absAtomicsPath

	// Resolve all input arguments
	for key, argDef := range test.InputArguments {
		value := toString(argDef.Default)
		value = resolveAtomicVariables(value, absAtomicsPath, finalArgs)
		finalArgs[key] = value
		sendLiveLog(taskID, fmt.Sprintf("[ARG] %s = %s", key, truncateString(value, 100)), false)
	}

	// Check if there are any dependencies
	if len(test.Dependencies) == 0 {
		sendLiveLog(taskID, "[*] No prerequisites defined for this test", false)
		return true
	}

	sendLiveLog(taskID, fmt.Sprintf("[*] Found %d prerequisite(s) to process", len(test.Dependencies)), false)
	sendLiveLog(taskID, "", false)

	// Get the executor for prereq commands
executor := getPrereqExecutor(test)
sendLiveLog(taskID, fmt.Sprintf("[*] Using executor: %s", executor), false)

allMet := true
for idx, dep := range test.Dependencies {
    sendLiveLog(taskID, "────────────────────────────────────────────────────────", false)
    sendLiveLog(taskID, fmt.Sprintf("[PREREQ %d/%d] %s", idx+1, len(test.Dependencies), dep.Description), false)

    // Resolve variables in prereq_command
    prereqCmd := resolveAtomicVariables(dep.PrereqCommand, absAtomicsPath, finalArgs)

    // IMPORTANT: Do NOT join multiline commands for PowerShell - it handles newlines correctly
    // Only join with && for cmd/batch executors
    if executor == "command_prompt" || executor == "cmd" {
        prereqCmd = strings.TrimSpace(prereqCmd)
        prereqCmd = strings.ReplaceAll(prereqCmd, "\n", " && ")
    }
    // For PowerShell, keep newlines intact - they're valid statement separators

		if prereqCmd == "" {
			sendLiveLog(taskID, "[SKIP] No prereq_command defined", false)
			continue
		}

		sendLiveLog(taskID, fmt.Sprintf("[CHECK] %s", truncateString(prereqCmd, 200)), false)

		// Run prereq check
		checkOutput := runPrereqCommand(prereqCmd, executor, taskID)

		// Determine if prereq is met
		isMet := isPrereqMet(checkOutput)

		if isMet {
			sendLiveLog(taskID, "[✓] Prerequisite already satisfied", false)
		} else {
			sendLiveLog(taskID, "[✗] Prerequisite NOT MET - attempting to install...", false)

			// Resolve variables in get_prereq_command
getPrereqCmd := resolveAtomicVariables(dep.GetPrereqCommand, absAtomicsPath, finalArgs)

// Only join with && for cmd/batch executors, NOT for PowerShell
if executor == "command_prompt" || executor == "cmd" {
    getPrereqCmd = strings.TrimSpace(getPrereqCmd)
    getPrereqCmd = strings.ReplaceAll(getPrereqCmd, "\n", " && ")
}

			if getPrereqCmd == "" {
				sendLiveLog(taskID, "[!] No get_prereq_command defined - cannot install", false)
				allMet = false
				continue
			}

			sendLiveLog(taskID, fmt.Sprintf("[INSTALL] %s", truncateString(getPrereqCmd, 200)), false)

			// Run get_prereq_command to install
			installOutput := runPrereqCommand(getPrereqCmd, executor, taskID)

			if installOutput.ExitCode == 0 {
				sendLiveLog(taskID, "[*] Installation command completed", false)

				// Re-check if prereq is now met
				sendLiveLog(taskID, "[*] Re-checking prerequisite...", false)
				recheckOutput := runPrereqCommand(prereqCmd, executor, taskID)

				if isPrereqMet(recheckOutput) {
					sendLiveLog(taskID, "[✓] Prerequisite now satisfied!", false)
				} else {
					sendLiveLog(taskID, "[!] Prerequisite still not met after installation", false)
					allMet = false
				}
			} else {
				sendLiveLog(taskID, fmt.Sprintf("[!] Installation failed (exit code: %d)", installOutput.ExitCode), false)
				allMet = false
			}
		}
	}

	sendLiveLog(taskID, "────────────────────────────────────────────────────────", false)
	sendLiveLog(taskID, "", false)

	if allMet {
		sendLiveLog(taskID, "[✓] All prerequisites satisfied!", true)
	} else {
		sendLiveLog(taskID, "[!] Some prerequisites could not be satisfied", true)
	}

	return allMet
}

// resolveAtomicVariables replaces all variable patterns in a string
func resolveAtomicVariables(text string, atomicsPath string, args map[string]string) string {
	if text == "" {
		return text
	}

	result := text

// Replace PathToAtomicsFolder variations (order matters - most specific first)
result = strings.ReplaceAll(result, "#{PathToAtomicsFolder}", atomicsPath)
result = strings.ReplaceAll(result, "${PathToAtomicsFolder}", atomicsPath)
result = strings.ReplaceAll(result, "$PathToAtomicsFolder", atomicsPath)
result = strings.ReplaceAll(result, "PathToAtomicsFolder", atomicsPath)

	// Replace other input arguments
	for key, value := range args {
		result = strings.ReplaceAll(result, fmt.Sprintf("#{%s}", key), value)
		result = strings.ReplaceAll(result, fmt.Sprintf("$%s", key), value)
		result = strings.ReplaceAll(result, fmt.Sprintf("${%s}", key), value)
	}

	// Expand environment variables
	result = os.ExpandEnv(result)

	// Normalize Windows paths containing ..
	if strings.Contains(result, "..") && runtime.GOOS == "windows" {
		result = normalizeWindowsPaths(result)
	}

	return result
}

// normalizeWindowsPaths resolves relative path sequences like ".." in Windows paths
// while preserving the original line structure
func normalizeWindowsPaths(text string) string {
	// Process line by line to preserve newlines
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		words := strings.Fields(line)
		for j, word := range words {
			// Check if this looks like a Windows path with ..
			if len(word) >= 3 && (word[1] == ':' || strings.HasPrefix(word, "\\\\")) && strings.Contains(word, "..") {
				cleanWord := strings.Trim(word, "\"'`;,")
				if resolved, err := filepath.Abs(cleanWord); err == nil {
					normalized := filepath.Clean(resolved)
					words[j] = strings.Replace(word, cleanWord, normalized, 1)
				}
			}
		}
		lines[i] = strings.Join(words, " ")
	}
	return strings.Join(lines, "\n")
}

// getPrereqExecutor determines which executor to use for prereq commands
func getPrereqExecutor(test AtomicTest) string {
	// Check if dependency_executor_name is specified
	if test.DependencyExecutorName != nil {
		if execName, ok := test.DependencyExecutorName.(string); ok && execName != "" {
			return strings.ToLower(execName)
		}
	}

	// Fall back to the test's executor
	executorName := strings.ToLower(test.Executor.Name)

	// For command_prompt tests, prereqs often use PowerShell
	if executorName == "command_prompt" || executorName == "cmd" {
		return "powershell"
	}

	return executorName
}

// runPrereqCommand executes a prerequisite command and captures output
func runPrereqCommand(command string, executor string, taskID string) CommandOutput {
	startTime := time.Now()
	cmdOutput := CommandOutput{
		Command:     command,
		StdoutLines: []string{},
		StderrLines: []string{},
		ExitCode:    0,
	}

	var cmd *exec.Cmd

	switch strings.ToLower(executor) {
case "powershell":
    // Keep original newlines - don't join with semicolons!
    cleanedCommand := strings.TrimSpace(command)
    
    // Wrap command to ensure proper error handling and output capture
    wrappedCmd := fmt.Sprintf(`
$ErrorActionPreference = 'Continue'
$ProgressPreference = 'SilentlyContinue'
try {
%s
} catch {
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
`, cleanedCommand)
    cmd = exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-Command", wrappedCmd)

	case "powershell_core", "pwsh":
		wrappedCmd := fmt.Sprintf(`
$ErrorActionPreference = 'Continue'
$ProgressPreference = 'SilentlyContinue'
try {
    %s
} catch {
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
`, command)
		cmd = exec.Command("pwsh.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-Command", wrappedCmd)

	case "command_prompt", "cmd":
		cmd = exec.Command("cmd.exe", "/C", command)
		// Hide the window on Windows
		if runtime.GOOS == "windows" {
			cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
		}

	case "bash":
		cmd = exec.Command("bash", "-c", command)

	case "sh":
		cmd = exec.Command("sh", "-c", command)

default:
    if runtime.GOOS == "windows" {
        // Keep original newlines intact - PowerShell handles them correctly
        // DO NOT join with semicolons as it breaks certain statements
        cleanedCommand := strings.TrimSpace(command)
        
        wrappedCmd := fmt.Sprintf(`
$ErrorActionPreference = 'Continue'
$ProgressPreference = 'SilentlyContinue'
try {
%s
} catch {
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
`, cleanedCommand)
        cmd = exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-Command", wrappedCmd)
    } else {
        cmd = exec.Command("sh", "-c", command)
    }
}
	// Capture output
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	// Run the command
	err := cmd.Run()

	// Process output
	if stdout.Len() > 0 {
		lines := strings.Split(strings.TrimSpace(stdout.String()), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line != "" {
				cmdOutput.StdoutLines = append(cmdOutput.StdoutLines, line)
				// Send to live log but don't spam with every line
				if len(cmdOutput.StdoutLines) <= 10 {
					sendLiveLog(taskID, "  "+line, false)
				}
			}
		}
		if len(cmdOutput.StdoutLines) > 10 {
			sendLiveLog(taskID, fmt.Sprintf("  ... and %d more lines", len(cmdOutput.StdoutLines)-10), false)
		}
	}

	if stderr.Len() > 0 {
		lines := strings.Split(strings.TrimSpace(stderr.String()), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line != "" {
				cmdOutput.StderrLines = append(cmdOutput.StderrLines, line)
				sendLiveLog(taskID, "  [STDERR] "+line, false)
			}
		}
	}

	// Get exit code
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			cmdOutput.ExitCode = exitErr.ExitCode()
		} else {
			cmdOutput.ExitCode = 1
		}
	}

	cmdOutput.ExecutionTime = time.Since(startTime)

	return cmdOutput
}

// isPrereqMet determines if a prerequisite check passed
func isPrereqMet(output CommandOutput) bool {
	// Exit code 0 usually means success
	if output.ExitCode != 0 {
		return false
	}

	// Check stdout for failure indicators
	fullOutput := strings.ToLower(output.GetFullOutput())

	// Common failure patterns
	failurePatterns := []string{
		"false",
		"not found",
		"not exist",
		"doesn't exist",
		"does not exist",
		"cannot find",
		"could not find",
		"missing",
		"not installed",
		"not met",
	}

	for _, pattern := range failurePatterns {
		if strings.Contains(fullOutput, pattern) {
			// But check for success patterns that might override
			successPatterns := []string{"true", "found", "exists", "installed", "met", "success", "passed"}
			hasSuccess := false
			for _, success := range successPatterns {
				if strings.Contains(fullOutput, success) {
					hasSuccess = true
					break
				}
			}
			if !hasSuccess {
				return false
			}
		}
	}

	return true
}



func handleShutdownTask(taskID string) {
	fmt.Println("[*] Received shutdown command, initiating self-destruct sequence...")

	exe, _ := os.Executable()
	exeDir := filepath.Dir(exe)
	exeName := filepath.Base(exe)

	fmt.Println("[*] Agent executable:", exe)
	fmt.Println("[*] Cleaning up all agent-related files...")

	// List of files/patterns to clean up
	cleanupPatterns := []string{
		"agent_config.json",
		"*.log",
		"atomic_modules",
		"AtomicRedTeam",
		"invoke-atomicredteam",
	}

	// Clean up files in agent directory
	for _, pattern := range cleanupPatterns {
		matches, err := filepath.Glob(filepath.Join(exeDir, pattern))
		if err == nil {
			for _, match := range matches {
				fmt.Println("[*] Removing:", match)
				os.RemoveAll(match)
			}
		}
	}

	// Remove from startup if configured
	if runtime.GOOS == "windows" {
		fmt.Println("[*] Removing from Windows startup...")
		
		// Remove from Run registry key
		exec.Command("reg", "delete", 
			"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
			"/v", "RedTeamAgent", "/f").Run()

		// Remove scheduled task if exists
		exec.Command("schtasks", "/delete", "/tn", "RedTeamAgent", "/f").Run()
		
		// Remove from Startup folder
		startupPath := filepath.Join(os.Getenv("APPDATA"), 
			"Microsoft\\Windows\\Start Menu\\Programs\\Startup", exeName)
		os.Remove(startupPath)
		os.Remove(startupPath + ".lnk")
	} else {
		fmt.Println("[*] Removing from Linux startup...")
		
		exec.Command("systemctl", "--user", "disable", "redteam-agent").Run()
		exec.Command("systemctl", "--user", "stop", "redteam-agent").Run()
		os.Remove(filepath.Join(os.Getenv("HOME"), ".config/systemd/user/redteam-agent.service"))
		exec.Command("sh", "-c", "crontab -l | grep -v 'redteam' | crontab -").Run()
		os.Remove("/tmp/redteam-agent")
	}

	// Clean up downloaded atomic modules
	homeDir, _ := os.UserHomeDir()
	atomicPaths := []string{
		filepath.Join(homeDir, "AtomicRedTeam"),
		filepath.Join(homeDir, "atomic_modules"),
		filepath.Join(exeDir, "AtomicRedTeam"),
		filepath.Join(exeDir, "atomic_modules"),
		"C:\\AtomicRedTeam",
		"C:\\Tools\\AtomicRedTeam",
	}

	for _, path := range atomicPaths {
		if _, err := os.Stat(path); err == nil {
			fmt.Println("[*] Removing atomic modules:", path)
			os.RemoveAll(path)
		}
	}

	// Clear any temp files created by agent
	tempPatterns := []string{
		filepath.Join(os.TempDir(), "redteam*"),
		filepath.Join(os.TempDir(), "atomic*"),
		filepath.Join(os.TempDir(), "art-*"),
	}

	for _, pattern := range tempPatterns {
		matches, _ := filepath.Glob(pattern)
		for _, match := range matches {
			fmt.Println("[*] Removing temp:", match)
			os.RemoveAll(match)
		}
	}

	fmt.Println("[*] Cleanup complete. Reporting status and terminating...")

	// Report completion before exit
	reportTask(map[string]interface{}{
		"task_id": taskID,
		"output":  "Agent shutdown complete. All files removed. Goodbye!",
		"status":  "completed",
	})

	time.Sleep(1 * time.Second)

	// Self-delete the executable
	if runtime.GOOS == "windows" {
		script := fmt.Sprintf(`@echo off
ping 127.0.0.1 -n 3 > nul
del /F /Q "%s"
rmdir /S /Q "%s\atomic_modules" 2>nul
rmdir /S /Q "%s\AtomicRedTeam" 2>nul
del /F /Q "%%~f0"
`, exe, exeDir, exeDir)
		
		batFile := filepath.Join(os.TempDir(), "cleanup_agent.bat")
		os.WriteFile(batFile, []byte(script), 0755)
		exec.Command("cmd", "/C", "start", "/MIN", batFile).Start()
	} else {
		script := fmt.Sprintf("sleep 3 && rm -f '%s' && rm -rf '%s/atomic_modules' && rm -rf '%s/AtomicRedTeam'", 
			exe, exeDir, exeDir)
		exec.Command("sh", "-c", fmt.Sprintf("nohup sh -c \"%s\" &", script)).Start()
	}

	fmt.Println("[*] Agent terminated. Goodbye!")
	os.Exit(0)
}

func handleUpdateConfig(task map[string]interface{}, taskID string) {
	fmt.Println("[*] Updating agent configuration...")

	config, ok := task["config"].(map[string]interface{})
	if !ok {
		reportTask(map[string]interface{}{
			"task_id": taskID,
			"output":  "ERROR: Invalid config format",
			"status":  "failed",
		})
		return
	}

	if val, ok := config["startup"].(bool); ok {
		agentConfig.Startup = val
	}
	if val, ok := config["jitter_time"].(float64); ok {
		agentConfig.JitterTime = int(val)
	}
	if val, ok := config["agent_info"].(string); ok {
		agentConfig.AgentInfo = val
	}
	if val, ok := config["security_level"].(string); ok {
		agentConfig.SecurityLevel = val
	}

	saveConfig()

	reportTask(map[string]interface{}{
		"task_id": taskID,
		"output":  "Configuration updated successfully",
		"status":  "completed",
	})
}

func handleFiledropTask(task map[string]interface{}, taskID string) {
	fmt.Println("[DEBUG] Filedrop task received:")
	fmt.Printf("[DEBUG] Task ID: %s\n", taskID)

	fname := toString(task["file"])
	if fname == "" {
		fmt.Println("[!] Filedrop task missing file parameter")
		reportTask(map[string]interface{}{
			"task_id": taskID,
			"output":  "ERROR: Missing file parameter",
			"status":  "failed",
		})
		return
	}

	fmt.Printf("[*] File to download: %s\n", fname)

	zipPath, err := downloadZip(fname)
	if err != nil {
		fmt.Println("[!] downloadZip() error:", err)
		reportTask(map[string]interface{}{
			"task_id": taskID,
			"output":  fmt.Sprintf("ERROR: Failed to download: %v", err),
			"status":  "failed",
		})
		return
	}

	fileInfo, err := os.Stat(zipPath)
	if err != nil {
		fmt.Println("[!] Cannot stat downloaded file:", err)
	} else {
		fmt.Printf("[*] Downloaded file size: %d bytes\n", fileInfo.Size())
	}

	fmt.Println("[*] Unzipping:", zipPath)
	if err := unzip(zipPath, AtomicsDir); err != nil {
		fmt.Println("[!] unzip error:", err)
		reportTask(map[string]interface{}{
			"task_id": taskID,
			"output":  fmt.Sprintf("ERROR: Failed to unzip: %v", err),
			"status":  "failed",
		})
		return
	}

	os.Remove(zipPath)
	fmt.Println("[*] Successfully extracted and removed ZIP")

	confirmFileDrop(taskID)

	reportTask(map[string]interface{}{
		"task_id": taskID,
		"output":  "Filedrop processed successfully",
		"status":  "completed",
	})
}

func handleExecuteTask(task map[string]interface{}, taskID string) {
	techs, _ := task["techniques"].([]interface{})

	fmt.Println("[*] Executing task:", taskID)
	fmt.Printf("[*] Found %d techniques to execute\n", len(techs))

	sendLiveLog(taskID, "[AGENT] Starting atomic test execution...", true)
	
	// Check if Invoke-AtomicRedTeam is available
	if invokeAtomicAvailable {
		sendLiveLog(taskID, "[AGENT] Using Invoke-AtomicRedTeam execution engine", true)
	} else {
		sendLiveLog(taskID, "[AGENT] Using direct execution mode (fallback)", true)
	}

	// Execute tests
	output := executeAtomicTestsGo(techs, taskID)
cleanupOrphanedCmd()
	sendLiveLog(taskID, "[AGENT] Execution completed", true)

	// Cleanup atomics folder after execution
	cleanupAtomics()
	sendLiveLog(taskID, "[AGENT] Cleanup completed - atomics folder cleaned", true)

	reportTask(map[string]interface{}{
		"task_id": taskID,
		"output":  output,
		"status":  "completed",
	})

	fmt.Println("[*] Task execution and cleanup finished for:", taskID)
}

// PART 3: Execution functions, test execution


func executeAtomicTestsGo(techs []interface{}, taskID string) string {
	var outputBuf bytes.Buffer
	var allResults []TestExecutionResult

	totalTests := len(techs)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] Starting execution of %d atomic test(s)", totalTests), true)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)

	for idx, techInterface := range techs {
		tech, ok := techInterface.(map[string]interface{})
		if !ok {
			fmt.Printf("[!] Could not parse technique at index %d\n", idx)
			continue
		}

		tid := toString(tech["id"])
		testIndexStr := toString(tech["test_index"])
		testName := toString(tech["test_name"])
		if testName == "" {
			testName = toString(tech["name"])
		}
		// Server-side resolver sends an expected GUID per test (the
		// auto_generated_guid from the matched YAML entry). Used below
		// as a safety-net check to catch stale atomics or resolver drift.
		expectedGuid := toString(tech["guid"])

		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ╔═══════════════════════════════════════════════════════════════"), false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ║ TEST %d of %d", idx+1, totalTests), false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ║ Technique ID: %s", tid), false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ║ Test Number: %s", testIndexStr), false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ║ Test Name: %s", testName), false)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ╚═══════════════════════════════════════════════════════════════"), false)

		testIndex := 0
		fmt.Sscanf(testIndexStr, "%d", &testIndex)

		// Safety-net pre-flight: peek at the on-disk YAML to verify GUID,
		// detect parent-fallback, and filter by platform BEFORE dispatching
		// to the execute path. If anything is off, record a skip and move
		// to the next test rather than running the wrong one.
		if yamlPath, ferr := findYamlForTechnique(tid); ferr == nil {
			if at, lerr := loadAtomicYaml(yamlPath); lerr == nil && testIndex < len(at.AtomicTests) {
				peek := at.AtomicTests[testIndex]

				// GUID mismatch - refuse to run, server and agent disagree
				if expectedGuid != "" && peek.AutoGeneratedGuid != "" &&
					!strings.EqualFold(expectedGuid, peek.AutoGeneratedGuid) {
					errMsg := fmt.Sprintf("[ERROR] GUID mismatch for %s test_index=%d: server expected %s, yaml has %s - skipping (agent atomics may be out of sync)",
						tid, testIndex, expectedGuid, peek.AutoGeneratedGuid)
					sendLiveLog(taskID, errMsg, true)
					outputBuf.WriteString(errMsg + "\n")

					skipResult := TestExecutionResult{
						TechniqueID: tid, TestNumber: testIndexStr, TestName: testName,
						Status: "skipped", StartTime: time.Now(), EndTime: time.Now(),
						ErrorMessages: []string{"GUID mismatch between server and agent atomics"},
					}
					allResults = append(allResults, skipResult)
					sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
					continue
				}

				// Parent YAML fallback - warn but continue
				if strings.Contains(tid, ".") && at.AttackTechnique != "" &&
					!strings.EqualFold(at.AttackTechnique, tid) {
					sendLiveLog(taskID, fmt.Sprintf("[INFO] Loaded parent YAML %s for sub-technique %s (test_index=%d)",
						at.AttackTechnique, tid, testIndex), false)
				}

				// Platform filter - skip if not runnable here
				if !isPlatformSupported(peek.SupportedPlatforms) {
					msg := fmt.Sprintf("[SKIP] %s test '%s' not supported on %s (platforms=%v)",
						tid, peek.Name, runtime.GOOS, peek.SupportedPlatforms)
					sendLiveLog(taskID, msg, true)
					outputBuf.WriteString(msg + "\n")

					skipResult := TestExecutionResult{
						TechniqueID: tid, TestNumber: testIndexStr, TestName: testName,
						Status: "skipped", StartTime: time.Now(), EndTime: time.Now(),
						ErrorMessages: []string{fmt.Sprintf("platform %s not supported", runtime.GOOS)},
					}
					allResults = append(allResults, skipResult)
					sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
					continue
				}
			}
		}

		inputArgs, _ := tech["input_args"].(map[string]interface{})

		var result TestExecutionResult

		if invokeAtomicAvailable {
			result = executeWithInvokeAtomic(tid, testIndex, testName, inputArgs, taskID)
		} else {
			yamlPath, err := findYamlForTechnique(tid)
if err != nil {
	errMsg := fmt.Sprintf("[ERROR] %v", err)
	sendLiveLog(taskID, errMsg, false)
	outputBuf.WriteString(errMsg + "\n")
	continue
}
atomicTech, err := loadAtomicYaml(yamlPath)
			if err != nil {
				errMsg := fmt.Sprintf("[ERROR] Failed to load YAML for %s: %v", tid, err)
				sendLiveLog(taskID, errMsg, false)
				outputBuf.WriteString(errMsg + "\n")
				sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
				continue
			}

			if testIndex >= len(atomicTech.AtomicTests) {
				errMsg := fmt.Sprintf("[ERROR] Test index %d out of range for %s", testIndex, tid)
				sendLiveLog(taskID, errMsg, false)
				outputBuf.WriteString(errMsg + "\n")
				sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
				continue
			}

			test := atomicTech.AtomicTests[testIndex]

			if test.Description != "" {
				sendLiveLog(taskID, fmt.Sprintf("[INFO] Description: %s", test.Description), false)
			}

			sendLiveLog(taskID, fmt.Sprintf("[INFO] Executor: %s", test.Executor.Name), false)
			sendLiveLog(taskID, fmt.Sprintf("[INFO] Platform(s): %s", strings.Join(test.SupportedPlatforms, ", ")), false)
			sendLiveLog(taskID, "", false)

			sendLiveLog(taskID, "[AGENT] ──────────────────── EXECUTION START ────────────────────", false)
			result = executeAtomicTest(tid, testIndex, test, inputArgs, taskID)
		}

// Only set TestNumber if not already set
		if result.TestNumber == "" {
			result.TestNumber = testIndexStr
		}
		allResults = append(allResults, result)

		outputBuf.WriteString(fmt.Sprintf("\n╔═══════════════════════════════════════════════════════════════\n"))
		outputBuf.WriteString(fmt.Sprintf("║ Test %d: %s (%s)\n", idx+1, testName, tid))
		outputBuf.WriteString(fmt.Sprintf("║ Status: %s\n", result.Status))
		outputBuf.WriteString(fmt.Sprintf("║ Duration: %.2f seconds\n", result.Duration.Seconds()))
		outputBuf.WriteString(fmt.Sprintf("╚═══════════════════════════════════════════════════════════════\n\n"))

		if len(result.PrereqOutput) > 0 {
			outputBuf.WriteString("──── Prerequisites Installation ────\n")
			for i, prereq := range result.PrereqOutput {
				outputBuf.WriteString(fmt.Sprintf("Prerequisite %d:\n", i+1))
				outputBuf.WriteString(prereq.GetFullOutput())
				outputBuf.WriteString("\n")
			}
		}

		if result.MainOutput.Command != "" {
			outputBuf.WriteString("──── Main Command Output ────\n")
			outputBuf.WriteString(fmt.Sprintf("Command: %s\n", truncateString(result.MainOutput.Command, 200)))
			outputBuf.WriteString(fmt.Sprintf("Exit Code: %d\n", result.MainOutput.ExitCode))
			outputBuf.WriteString(fmt.Sprintf("Execution Time: %.2f seconds\n\n", result.MainOutput.ExecutionTime.Seconds()))

			if len(result.MainOutput.StdoutLines) > 0 {
				outputBuf.WriteString("STDOUT:\n")
				for _, line := range result.MainOutput.StdoutLines {
					outputBuf.WriteString(line + "\n")
				}
				outputBuf.WriteString("\n")
			}

			if len(result.MainOutput.StderrLines) > 0 {
				outputBuf.WriteString("STDERR:\n")
				for _, line := range result.MainOutput.StderrLines {
					outputBuf.WriteString(line + "\n")
				}
				outputBuf.WriteString("\n")
			}
		}

		if result.CleanupOutput.Command != "" {
			outputBuf.WriteString("──── Cleanup Output ────\n")
			outputBuf.WriteString(result.CleanupOutput.GetFullOutput())
			outputBuf.WriteString("\n")
		}

		outputBuf.WriteString("\n")

		sendLiveLog(taskID, "[AGENT] ──────────────────── EXECUTION END ──────────────────────", false)

		statusIcon := "✓"
		if result.Status == "failed" {
			statusIcon = "✗"
		} else if result.Status == "skipped" {
			statusIcon = "⊘"
		}

		sendLiveLog(taskID, fmt.Sprintf("[%s] Test %d of %d: %s (%.2fs)", statusIcon, idx+1, totalTests, result.Status, result.Duration.Seconds()), true)
		sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)
	}

	sendLiveLog(taskID, "", false)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)

	completed := 0
	failed := 0
	skipped := 0
	totalDuration := 0.0

	for _, r := range allResults {
		switch r.Status {
		case "completed":
			completed++
		case "failed":
			failed++
		case "skipped":
			skipped++
		}
		totalDuration += r.Duration.Seconds()
	}

	sendLiveLog(taskID, fmt.Sprintf("[SUMMARY] Total Tests: %d | Completed: %d | Failed: %d | Skipped: %d", totalTests, completed, failed, skipped), true)
	sendLiveLog(taskID, fmt.Sprintf("[SUMMARY] Total Execution Time: %.2f seconds", totalDuration), true)
	sendLiveLog(taskID, fmt.Sprintf("[AGENT] ═══════════════════════════════════════════════════════════════"), false)

	outputBuf.WriteString("\n═══════════════════ EXECUTION SUMMARY ═══════════════════\n")
	outputBuf.WriteString(fmt.Sprintf("Total Tests: %d\n", totalTests))
	outputBuf.WriteString(fmt.Sprintf("✓ Completed: %d\n", completed))
	outputBuf.WriteString(fmt.Sprintf("✗ Failed: %d\n", failed))
	outputBuf.WriteString(fmt.Sprintf("⊘ Skipped: %d\n", skipped))
	outputBuf.WriteString(fmt.Sprintf("Total Time: %.2f seconds\n", totalDuration))
	outputBuf.WriteString("═══════════════════════════════════════════════════════════\n")

	return outputBuf.String()
}

func executeWithInvokeAtomic(tid string, testIndex int, testName string, inputArgs map[string]interface{}, taskID string) TestExecutionResult {
	result := TestExecutionResult{
		TechniqueID:   tid,
		TestNumber:    fmt.Sprintf("%d", testIndex),
		TestName:      testName,
		Status:        "running",
		PrereqOutput:  []CommandOutput{},
		ErrorMessages: []string{},
		StartTime:     time.Now(),
	}
	// FIX: Prevent nil map panic
	if inputArgs == nil {
		inputArgs = make(map[string]interface{})
	}

	// FIX 3: Check if this is a manual test by loading YAML first
	yamlPath, err := findYamlForTechnique(tid)
	if err == nil {
		atomicTech, err := loadAtomicYaml(yamlPath)
		if err == nil && testIndex < len(atomicTech.AtomicTests) {
			test := atomicTech.AtomicTests[testIndex]
			executorName := strings.ToLower(test.Executor.Name)
			
			// Handle manual tests
			if executorName == "manual" {
				sendLiveLog(taskID, "╔═══════════════════════════════════════════════════════════════", false)
				sendLiveLog(taskID, "║ MANUAL TEST - Requires Human Interaction", false)
				sendLiveLog(taskID, "╚═══════════════════════════════════════════════════════════════", false)
				sendLiveLog(taskID, "", false)
				sendLiveLog(taskID, fmt.Sprintf("[TEST] %s", test.Name), false)
				sendLiveLog(taskID, fmt.Sprintf("[DESC] %s", test.Description), false)
				sendLiveLog(taskID, "", false)
				sendLiveLog(taskID, "[STEPS] Manual steps required:", false)
				
				steps := strings.Split(test.Executor.Command, "\n")
				for _, step := range steps {
					if strings.TrimSpace(step) != "" {
						sendLiveLog(taskID, "  → "+strings.TrimSpace(step), false)
					}
				}
				
				sendLiveLog(taskID, "", false)
				sendLiveLog(taskID, "[SKIP] This test cannot be automated - please perform manually", true)
				
				result.Status = "skipped"
				result.ErrorMessages = append(result.ErrorMessages, "Manual test requires operator intervention")
				result.EndTime = time.Now()
				result.Duration = result.EndTime.Sub(result.StartTime)
				sendTestResult(taskID, result)
				return result
			}
			
			// FIX 5: Check elevation requirement
			if test.Executor.ElevationRequired && !isElevated() {
				sendLiveLog(taskID, "[WARNING] This test requires elevation (admin/root) but agent is not running elevated!", true)
				sendLiveLog(taskID, "[WARNING] Test may fail or produce incomplete results", false)
			}
		}
	}

	sendLiveLog(taskID, "[MODE] Using Invoke-AtomicTest for execution", false)
	sendLiveLog(taskID, "[AGENT] ──────────────────── EXECUTION START ────────────────────", false)

	absAtomicsPath, _ := filepath.Abs(AtomicsDir)

	iatPsd1, errIAT := findFileRecursive(InvokeAtomicModuleDir, "Invoke-AtomicRedTeam.psd1")
	yamlPsd1, errYAML := findFileRecursive(InvokeAtomicModuleDir, PowershellYamlPsd1)

	if errIAT != nil || errYAML != nil {
		msg := fmt.Sprintf("[ERROR] Module PSD1 files not found. IAT=%v YAML=%v", errIAT, errYAML)
		sendLiveLog(taskID, msg, false)
		result.Status = "failed"
		result.ErrorMessages = append(result.ErrorMessages, msg)
		result.EndTime = time.Now()
		result.Duration = result.EndTime.Sub(result.StartTime)
		sendTestResult(taskID, result)
		return result
	}

	harnessPsd1, errHarness := findFileRecursive(InvokeAtomicModuleDir, AtomicTestHarnessesPsd1)
	harnessAvailable := errHarness == nil

	absIatPsd1, _ := filepath.Abs(iatPsd1)
	absYamlPsd1, _ := filepath.Abs(yamlPsd1)
	absIatPsd1 = strings.ReplaceAll(absIatPsd1, "\\", "/")
	absYamlPsd1 = strings.ReplaceAll(absYamlPsd1, "\\", "/")
	absAtomicsPath = strings.ReplaceAll(absAtomicsPath, "\\", "/")

	harnessImport := ""
	if harnessAvailable {
		absHarnessPsd1, _ := filepath.Abs(harnessPsd1)
		absHarnessPsd1 = strings.ReplaceAll(absHarnessPsd1, "\\", "/")
		harnessImport = fmt.Sprintf(`
try { Import-Module '%s' -Force -ErrorAction SilentlyContinue } catch {}
`, absHarnessPsd1)
	}

	inputArgsStr := ""
	if len(inputArgs) > 0 {
		sendLiveLog(taskID, "[INFO] Input Arguments:", false)
		var sb strings.Builder
		sb.WriteString("$InputArgs = @{\n")
		for key, val := range inputArgs {
			valStr := toString(val)
			sendLiveLog(taskID, fmt.Sprintf("  • %s = %s", key, truncateString(valStr, 100)), false)
			valStr = strings.ReplaceAll(valStr, "'", "''")
			key = strings.ReplaceAll(key, "'", "''")
			sb.WriteString(fmt.Sprintf("    '%s' = '%s'\n", key, valStr))
		}
		sb.WriteString("}\n$params['InputArgs'] = $InputArgs\n")
		inputArgsStr = sb.String()
	}

	psCmd := fmt.Sprintf(`
$ErrorActionPreference = 'Continue'
$VerbosePreference = 'SilentlyContinue'
$DebugPreference = 'SilentlyContinue'

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

Import-Module '%s' -Force -Verbose:$false -WarningAction SilentlyContinue
Import-Module '%s' -Force -Verbose:$false -WarningAction SilentlyContinue
%s

$atomicsPath = '%s'
$technique = '%s'  
$testNum = %d
$externalPayloads = Join-Path (Split-Path $atomicsPath -Parent) "ExternalPayloads"
if (-not (Test-Path $externalPayloads)) {
    New-Item -ItemType Directory -Path $externalPayloads -Force | Out-Null
    Write-Host "[*] Created ExternalPayloads folder: $externalPayloads"
}
Write-Host "========================================================"
Write-Host "ATOMIC TEST EXECUTION"
Write-Host "Technique: $technique | Test Number: $testNum"
Write-Host "Atomics Path: $atomicsPath"
Write-Host "========================================================"
Write-Host ""

$yamlPath = Join-Path $atomicsPath "$technique\$technique.yaml"
if (-not (Test-Path $yamlPath)) {
    Write-Host "[ERROR] YAML not found: $yamlPath"
    exit 1
}

Write-Host "[*] Loading test definition from: $yamlPath"
$yamlContent = Get-Content $yamlPath -Raw
$atomic = ConvertFrom-Yaml $yamlContent

$test = $atomic.atomic_tests[$testNum]
if (-not $test) {
    Write-Host "[ERROR] Test number $testNum not found"
    exit 1
}

Write-Host ""
Write-Host "========================================================"
Write-Host "TEST DETAILS"
Write-Host "========================================================"
Write-Host "Name: $($test.name)"
Write-Host "Description: $($test.description)"
Write-Host "Platforms: $($test.supported_platforms -join ', ')"
Write-Host "Executor: $($test.executor.name)"
Write-Host "Elevation Required: $($test.executor.elevation_required)"
Write-Host ""

function Replace-AllVariables {
    param([string]$text, [hashtable]$argHash)
    
    if ([string]::IsNullOrEmpty($text)) { return $text }
    
    $result = $text
    $result = $result.Replace('#{PathToAtomicsFolder}', $atomicsPath)
    $result = $result.Replace('$PathToAtomicsFolder', $atomicsPath)
    $result = $result.Replace('PathToAtomicsFolder', $atomicsPath)
    
    if ($argHash) {
        foreach ($key in $argHash.Keys) {
            $result = $result.Replace("#{$key}", $argHash[$key])
        }
    }
    
    $result = [System.Environment]::ExpandEnvironmentVariables($result)
    
    # FIX 4: Normalize paths containing ..
    if ($result -match '\.\.') {
        $result = [regex]::Replace($result, '([A-Za-z]:[\\/][^\s"'';<>|]+)', {
            param($match)
            $path = $match.Groups[1].Value
            if ($path -match '\.\.') {
                try {
                    $normalized = [System.IO.Path]::GetFullPath($path)
                    return $normalized
                } catch { return $path }
            }
            return $path
        })
    }
    
    return $result
}

$inputArgs = @{}
if ($test.input_arguments) {
    Write-Host "========================================================"
    Write-Host "INPUT ARGUMENTS (with resolved values)"
    Write-Host "========================================================"
    foreach ($arg in $test.input_arguments.GetEnumerator()) {
        $rawValue = [string]$arg.Value.default
        $resolvedValue = Replace-AllVariables -text $rawValue -argHash $inputArgs
        $inputArgs[$arg.Key] = $resolvedValue
        Write-Host "  $($arg.Key):"
        Write-Host "    Raw: $rawValue"
        Write-Host "    Resolved: $resolvedValue"
    }
    Write-Host ""
}

%s

function Execute-Command {
    param(
        [string]$rawCommand,
        [string]$executor,
        [string]$label
    )
    
    $command = Replace-AllVariables -text $rawCommand -argHash $inputArgs
    
    Write-Host ""
    Write-Host "========================================================"
    Write-Host "[$label]"
    Write-Host "========================================================"
    Write-Host "Executor: $executor"
    Write-Host ""
    Write-Host "Raw Command:"
    Write-Host $rawCommand
    Write-Host ""
    Write-Host "Resolved Command:"
    Write-Host $command
    Write-Host ""
    Write-Host "-------------------- OUTPUT START --------------------"
    
    $startTime = Get-Date
    
    try {
        if ($executor -eq "command_prompt" -or $executor -eq "cmd") {
            $pinfo = New-Object System.Diagnostics.ProcessStartInfo
            $pinfo.FileName = "cmd.exe"
            $pinfo.Arguments = "/c $command"
            $pinfo.RedirectStandardOutput = $true
            $pinfo.RedirectStandardError = $true
            $pinfo.UseShellExecute = $false
            $pinfo.CreateNoWindow = $true
            
            $p = New-Object System.Diagnostics.Process
            $p.StartInfo = $pinfo
            $p.Start() | Out-Null
            
            $stdout = $p.StandardOutput.ReadToEnd()
            $stderr = $p.StandardError.ReadToEnd()
            $p.WaitForExit()
            
            if ($stdout) { Write-Host $stdout }
            if ($stderr) { Write-Host "[STDERR] $stderr" }
            Write-Host "[Exit Code: $($p.ExitCode)]"
        }
        else {
            $output = Invoke-Expression $command 2>&1
            foreach ($line in $output) {
                Write-Host $line
            }
        }
    } catch {
        Write-Host "[EXCEPTION] $($_.Exception.Message)"
    }
    
    $endTime = Get-Date
    $duration = ($endTime - $startTime).TotalSeconds
    
    Write-Host "-------------------- OUTPUT END ----------------------"
    Write-Host "Duration: $duration seconds"
}
                


Write-Host ""
Write-Host "========================================================"
Write-Host "MAIN COMMAND EXECUTION"
Write-Host "========================================================"
if ($test.executor.command) {
    Execute-Command -rawCommand $test.executor.command -executor $test.executor.name -label "MAIN COMMAND"
} else {
    Write-Host "[!] No command defined for this test"
}

Write-Host ""
Write-Host "========================================================"
Write-Host "CLEANUP"
Write-Host "========================================================"
if ($test.executor.cleanup_command) {
    $cleanupCmd = Replace-AllVariables -text $test.executor.cleanup_command -argHash $inputArgs
    Write-Host "Command: $cleanupCmd"
    Write-Host ""
    Write-Host "-------------------- CLEANUP OUTPUT --------------------"
    try {
        if ($test.executor.name -eq "command_prompt" -or $test.executor.name -eq "cmd") {
            $pinfo = New-Object System.Diagnostics.ProcessStartInfo
            $pinfo.FileName = "cmd.exe"
            $pinfo.Arguments = "/c $cleanupCmd"
            $pinfo.RedirectStandardOutput = $true
            $pinfo.RedirectStandardError = $true
            $pinfo.UseShellExecute = $false
            $pinfo.CreateNoWindow = $true
            
            $p = New-Object System.Diagnostics.Process
            $p.StartInfo = $pinfo
            $p.Start() | Out-Null
            
            $stdout = $p.StandardOutput.ReadToEnd()
            $stderr = $p.StandardError.ReadToEnd()
            $p.WaitForExit()
            
            if ($stdout) { Write-Host $stdout }
            if ($stderr) { Write-Host "[STDERR] $stderr" }
            Write-Host "[Exit Code: $($p.ExitCode)]"
        } else {
            $cleanupOutput = Invoke-Expression $cleanupCmd 2>&1
            if ($cleanupOutput) {
                $cleanupOutput | ForEach-Object { Write-Host $_ }
            }
        }
        Write-Host "-------------------- END CLEANUP -----------------------"
        Write-Host "[OK] Cleanup completed"
    } catch {
        Write-Host "[!] Cleanup failed: $($_.Exception.Message)"
    }
} else {
    Write-Host "(none defined)"
}

Write-Host ""
Write-Host "========================================================"
Write-Host "TEST COMPLETE"
Write-Host "========================================================"
`, absYamlPsd1, absIatPsd1, harnessImport, absAtomicsPath, tid, testIndex, inputArgsStr)

	sendLiveLog(taskID, "", false)
	sendLiveLog(taskID, "[OUTPUT] **************************************************************************", false)

	cmdOutput := runCommandDetailed(psCmd, "powershell", taskID)
	result.MainOutput = cmdOutput

	sendLiveLog(taskID, "[OUTPUT] **************************************************************************", false)
	sendLiveLog(taskID, "", false)

	if cmdOutput.ExitCode != 0 {
		result.Status = "failed"
		result.ErrorMessages = append(result.ErrorMessages, cmdOutput.GetStderr())
	} else {
		fullOutput := strings.ToLower(cmdOutput.GetFullOutput())
		if strings.Contains(fullOutput, "prerequisites not met") ||
			strings.Contains(fullOutput, "failed") ||
			strings.Contains(fullOutput, "error executing") {
			result.Status = "failed"
		} else {
			result.Status = "completed"
		}
	}

	result.EndTime = time.Now()
	result.Duration = result.EndTime.Sub(result.StartTime)

	sendTestResult(taskID, result)
	sendCommandOutput(taskID, tid, result.TestNumber, "main", result.MainOutput)

	return result
}

func executeAtomicTest(tid string, testIndex int, test AtomicTest, inputArgs map[string]interface{}, taskID string) TestExecutionResult {
	result := TestExecutionResult{
		TechniqueID:   tid,
		TestNumber:    fmt.Sprintf("%d", testIndex), 
		TestName:      test.Name,
		Status:        "running",
		PrereqOutput:  []CommandOutput{},
		ErrorMessages: []string{},
		StartTime:     time.Now(),
	}
		// FIX: Prevent nil map panic
	if inputArgs == nil {
		inputArgs = make(map[string]interface{})
	}

	// FIX 3: Handle manual tests
	if strings.ToLower(test.Executor.Name) == "manual" {
		sendLiveLog(taskID, "╔═══════════════════════════════════════════════════════════════", false)
		sendLiveLog(taskID, "║ MANUAL TEST - Requires Human Interaction", false)
		sendLiveLog(taskID, "╚═══════════════════════════════════════════════════════════════", false)
		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, fmt.Sprintf("[TEST] %s", test.Name), false)
		sendLiveLog(taskID, fmt.Sprintf("[DESC] %s", test.Description), false)
		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, "[STEPS] Manual steps required:", false)
		
		steps := strings.Split(test.Executor.Command, "\n")
		for _, step := range steps {
			if strings.TrimSpace(step) != "" {
				sendLiveLog(taskID, "  → "+strings.TrimSpace(step), false)
			}
		}
		
		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, "[SKIP] This test cannot be automated - please perform manually", true)
		
		result.Status = "skipped"
		result.ErrorMessages = append(result.ErrorMessages, "Manual test requires operator intervention")
		result.EndTime = time.Now()
		result.Duration = result.EndTime.Sub(result.StartTime)
		sendTestResult(taskID, result)
		return result
	}

	// FIX 5: Check elevation requirement
	if test.Executor.ElevationRequired && !isElevated() {
		sendLiveLog(taskID, "[WARNING] ⚠ This test requires elevation (admin/root) but agent is not running elevated!", true)
		sendLiveLog(taskID, "[WARNING] Test may fail or produce incomplete results", false)
	}

	if !isPlatformSupported(test.SupportedPlatforms) {
		msg := fmt.Sprintf("[SKIP] Test not supported on platform: %s", runtime.GOOS)
		sendLiveLog(taskID, msg, false)
		result.Status = "skipped"
		result.ErrorMessages = append(result.ErrorMessages, msg)
		result.EndTime = time.Now()
		result.Duration = result.EndTime.Sub(result.StartTime)
		return result
	}

	absAtomicsPath, _ := filepath.Abs(AtomicsDir)
	finalArgs := make(map[string]string)
	finalArgs["PathToAtomicsFolder"] = absAtomicsPath

	for key, argDef := range test.InputArguments {
		if val, ok := inputArgs[key]; ok {
			finalArgs[key] = toString(val)
		} else {
			finalArgs[key] = toString(argDef.Default)
		}
	}

	if len(test.Dependencies) > 0 {
		sendLiveLog(taskID, fmt.Sprintf("[PREREQ] Found %d prerequisite(s)", len(test.Dependencies)), false)

		for idx, dep := range test.Dependencies {
			sendLiveLog(taskID, fmt.Sprintf("[PREREQ %d] %s", idx+1, dep.Description), false)

			if dep.PrereqCommand != "" {
				prereqCmd := replaceVariables(dep.PrereqCommand, finalArgs)
				sendLiveLog(taskID, fmt.Sprintf("[CHECK] %s", truncateString(prereqCmd, 150)), false)

				checkOutput := runCommandDetailed(prereqCmd, test.Executor.Name, taskID)
				result.PrereqOutput = append(result.PrereqOutput, checkOutput)

				isMet := checkOutput.ExitCode == 0
				outputStr := strings.ToLower(checkOutput.GetFullOutput())
				if strings.Contains(outputStr, "false") || strings.Contains(outputStr, "not found") {
					isMet = false
				}

				if isMet {
					sendLiveLog(taskID, "[OK] Prerequisite satisfied", false)
				} else {
					sendLiveLog(taskID, "[!] Prerequisite NOT MET - attempting to install...", false)

					if dep.GetPrereqCommand != "" {
						getCmd := replaceVariables(dep.GetPrereqCommand, finalArgs)
						sendLiveLog(taskID, fmt.Sprintf("[INSTALL] %s", truncateString(getCmd, 150)), false)

						installOutput := runCommandDetailed(getCmd, test.Executor.Name, taskID)
						result.PrereqOutput = append(result.PrereqOutput, installOutput)

						if installOutput.ExitCode == 0 {
							sendLiveLog(taskID, "[OK] Prerequisite installed", false)
						} else {
							sendLiveLog(taskID, "[!] Installation may have failed", false)
						}
					}
				}
			}
		}
	}

	if test.Executor.Command != "" {
		sendLiveLog(taskID, "[STEP] Executing main command...", false)
		command := replaceVariables(test.Executor.Command, finalArgs)

		sendLiveLog(taskID, fmt.Sprintf("[COMMAND] %s", truncateString(command, 300)), false)
		sendLiveLog(taskID, "", false)
		sendLiveLog(taskID, "[OUTPUT] ************************************************", false)

		result.MainOutput = runCommandDetailed(command, test.Executor.Name, taskID)

		sendLiveLog(taskID, "[OUTPUT] ************************************************", false)

		sendCommandOutput(taskID, tid, result.TestNumber, "main", result.MainOutput)

		if result.MainOutput.HasErrors() {
			result.Status = "failed"
		}
	}

	if test.Executor.CleanupCommand != "" {
		sendLiveLog(taskID, "[STEP] Running cleanup...", false)
		cleanupCmd := replaceVariables(test.Executor.CleanupCommand, finalArgs)
		result.CleanupOutput = runCommandDetailed(cleanupCmd, test.Executor.Name, taskID)
		sendCommandOutput(taskID, tid, result.TestNumber, "cleanup", result.CleanupOutput)
	}

	if result.Status != "failed" && result.Status != "skipped" {
		result.Status = "completed"
	}

	result.EndTime = time.Now()
	result.Duration = result.EndTime.Sub(result.StartTime)

	sendTestResult(taskID, result)

	return result
}

// PART 4: Live logging (WITH MUTEX/RETRY FIXES), helpers, YAML parsing, utilities


// FIX: sendLiveLog with mutex protection and retry logic
func sendLiveLog(taskID, line string, agentComment bool) {
	sendLiveLogWithType(taskID, line, agentComment, "")
}

// FIX: sendLiveLogWithType with mutex to prevent race conditions and retry logic
func sendLiveLogWithType(taskID, line string, agentComment bool, outputType string) {
	logMutex.Lock()
	defer logMutex.Unlock()

	report := map[string]interface{}{
		"task_id":   taskID,
		"output":    line,
		"partial":   true,
		"timestamp": time.Now().UnixMilli(), // Use milliseconds for better ordering
	}

	if agentComment {
		report["agent_comment"] = true
	}

	if outputType != "" {
		report["output_type"] = outputType
	}

	data, _ := json.Marshal(report)

	// FIX: Retry up to 3 times with delay
	var lastErr error
	for attempt := 0; attempt < 3; attempt++ {
		req, err := http.NewRequest("POST", ServerURL+"/api/report/"+AgentID, bytes.NewReader(data))
		if err != nil {
			lastErr = err
			continue
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("X-AGENT-TOKEN", AdminToken)

		// FIX: Use timeout to prevent hanging
		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(req)
		if err != nil {
			lastErr = err
			time.Sleep(100 * time.Millisecond)
			continue
		}

		resp.Body.Close()

		if resp.StatusCode == 200 {
			return // Success
		}

		lastErr = fmt.Errorf("server returned %d", resp.StatusCode)
		time.Sleep(100 * time.Millisecond)
	}

	// Only print error on final failure (don't spam logs)
	if lastErr != nil {
		fmt.Printf("[!] sendLiveLog failed after retries: %v\n", lastErr)
	}
}

// FIX: runCommandDetailed with improved real-time streaming and larger buffers
func runCommandDetailed(command string, executor string, taskID string) CommandOutput {
	startTime := time.Now()
	cmdOutput := CommandOutput{
		Command:     command,
		StdoutLines: []string{},
		StderrLines: []string{},
		ExitCode:    0,
	}

	var cmd *exec.Cmd

	switch strings.ToLower(executor) {
	case "powershell":
		cmd = exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", command)
	case "powershell_core", "pwsh":
		cmd = exec.Command("pwsh.exe", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", command)
	case "command_prompt", "cmd":
		cmd = exec.Command("cmd.exe", "/C", command)
	case "bash":
		cmd = exec.Command("bash", "-c", command)
	case "sh":
		cmd = exec.Command("sh", "-c", command)
	default:
		if runtime.GOOS == "windows" {
			cmd = exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", command)
		} else {
			cmd = exec.Command("sh", "-c", command)
		}
	}

	cmd.Env = append(os.Environ(),
		"PYTHONUNBUFFERED=1",
		"POWERSHELL_TELEMETRY_OPTOUT=1",
	)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		errMsg := fmt.Sprintf("Error creating stdout pipe: %v", err)
		cmdOutput.StderrLines = append(cmdOutput.StderrLines, errMsg)
		cmdOutput.ExitCode = 1
		sendLiveLog(taskID, "[ERROR] "+errMsg, false)
		return cmdOutput
	}

	stderr, err := cmd.StderrPipe()
	if err != nil {
		errMsg := fmt.Sprintf("Error creating stderr pipe: %v", err)
		cmdOutput.StderrLines = append(cmdOutput.StderrLines, errMsg)
		cmdOutput.ExitCode = 1
		sendLiveLog(taskID, "[ERROR] "+errMsg, false)
		return cmdOutput
	}

	if err := cmd.Start(); err != nil {
		errMsg := fmt.Sprintf("Error starting command: %v", err)
		cmdOutput.StderrLines = append(cmdOutput.StderrLines, errMsg)
		cmdOutput.ExitCode = 1
		sendLiveLog(taskID, "[ERROR] "+errMsg, false)
		return cmdOutput
	}

	var wg sync.WaitGroup
	wg.Add(2)

	// FIX: Mutex to protect slice appends
	var outputMutex sync.Mutex

	// Read stdout in real-time
	go func() {
		defer wg.Done()
		scanner := bufio.NewScanner(stdout)
		buf := make([]byte, 0, 256*1024)
		scanner.Buffer(buf, 2*1024*1024)

		for scanner.Scan() {
			line := scanner.Text()
			
			// FIX: Thread-safe append
			outputMutex.Lock()
			cmdOutput.StdoutLines = append(cmdOutput.StdoutLines, line)
			outputMutex.Unlock()

			if taskID != "" {
				sendLiveLogWithType(taskID, line, false, "stdout")
			}
			fmt.Println(line)
		}

		if err := scanner.Err(); err != nil {
			fmt.Println("[!] Scanner error on stdout:", err)
		}
	}()

	// Read stderr in real-time
	go func() {
		defer wg.Done()
		scanner := bufio.NewScanner(stderr)
		buf := make([]byte, 0, 256*1024)
		scanner.Buffer(buf, 2*1024*1024)

		for scanner.Scan() {
			line := scanner.Text()
			
			// FIX: Thread-safe append
			outputMutex.Lock()
			cmdOutput.StderrLines = append(cmdOutput.StderrLines, line)
			outputMutex.Unlock()

			stderrLine := "[STDERR] " + line
			if taskID != "" {
				sendLiveLogWithType(taskID, stderrLine, false, "stderr")
			}
			fmt.Println(stderrLine)
		}

		if err := scanner.Err(); err != nil {
			fmt.Println("[!] Scanner error on stderr:", err)
		}
	}()

	wg.Wait()

	err = cmd.Wait()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			cmdOutput.ExitCode = exitErr.ExitCode()
		} else {
			cmdOutput.ExitCode = 1
		}
	}

	cmdOutput.ExecutionTime = time.Since(startTime)

	if taskID != "" {
		summary := fmt.Sprintf("[AGENT] Command finished: %d stdout lines, %d stderr lines, exit code %d, duration %.2fs",
			len(cmdOutput.StdoutLines), len(cmdOutput.StderrLines), cmdOutput.ExitCode, cmdOutput.ExecutionTime.Seconds())
		sendLiveLog(taskID, summary, true)
	}

	return cmdOutput
}

// CommandOutput helper methods
func (co CommandOutput) GetFullOutput() string {
	var buf bytes.Buffer
	for _, line := range co.StdoutLines {
		buf.WriteString(line + "\n")
	}
	for _, line := range co.StderrLines {
		buf.WriteString("[STDERR] " + line + "\n")
	}
	return buf.String()
}

func (co CommandOutput) GetStdout() string {
	return strings.Join(co.StdoutLines, "\n")
}

func (co CommandOutput) GetStderr() string {
	return strings.Join(co.StderrLines, "\n")
}

func (co CommandOutput) HasErrors() bool {
	return co.ExitCode != 0 || len(co.StderrLines) > 0
}

func sendTestResult(taskID string, result TestExecutionResult) {
	report := map[string]interface{}{
		"task_id":       taskID,
		"result_type":   "test_execution",
		"technique_id":  result.TechniqueID,
		"test_number":   result.TestNumber,
		"test_name":     result.TestName,
		"status":        result.Status,
		"duration":      result.Duration.Seconds(),
		"start_time":    result.StartTime.Unix(),
		"end_time":      result.EndTime.Unix(),
		"partial":       true,
		"mitre_version": MitreVersion,
	}

	if result.MainOutput.Command != "" {
		report["main_command"] = map[string]interface{}{
			"command":        truncateString(result.MainOutput.Command, 500),
			"exit_code":      result.MainOutput.ExitCode,
			"execution_time": result.MainOutput.ExecutionTime.Seconds(),
			"stdout_lines":   len(result.MainOutput.StdoutLines),
			"stderr_lines":   len(result.MainOutput.StderrLines),
			"has_errors":     result.MainOutput.HasErrors(),
		}
	}

	if len(result.ErrorMessages) > 0 {
		report["errors"] = result.ErrorMessages
	}

	data, _ := json.Marshal(report)

	req, _ := http.NewRequest("POST", ServerURL+"/api/report/"+AgentID, bytes.NewReader(data))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-AGENT-TOKEN", AdminToken)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("[!] sendTestResult error:", err)
		return
	}
	resp.Body.Close()
}
func sendCommandOutput(taskID string, techniqueID string, testNumber string, commandType string, cmdOutput CommandOutput) {
	report := map[string]interface{}{
		"task_id":        taskID,
		"result_type":    "command_output",
		"technique_id":   techniqueID,
		"test_number":    testNumber,  // NEW
		"command_type":   commandType,
		"command":        truncateString(cmdOutput.Command, 500),
		"exit_code":      cmdOutput.ExitCode,
		"execution_time": cmdOutput.ExecutionTime.Seconds(),
		"timestamp":      time.Now().Unix(),
		"partial":        true,
	}

	if len(cmdOutput.StdoutLines) > 0 {
		report["stdout"] = strings.Join(cmdOutput.StdoutLines, "\n")
		report["stdout_line_count"] = len(cmdOutput.StdoutLines)
	}

	if len(cmdOutput.StderrLines) > 0 {
		report["stderr"] = strings.Join(cmdOutput.StderrLines, "\n")
		report["stderr_line_count"] = len(cmdOutput.StderrLines)
	}

	data, _ := json.Marshal(report)

	req, _ := http.NewRequest("POST", ServerURL+"/api/report/"+AgentID, bytes.NewReader(data))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-AGENT-TOKEN", AdminToken)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return
	}
	resp.Body.Close()
}

func reportTask(report map[string]interface{}) {
	data, _ := json.Marshal(report)

	req, _ := http.NewRequest("POST", ServerURL+"/api/report/"+AgentID, bytes.NewReader(data))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-AGENT-TOKEN", AdminToken)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("[!] reportTask HTTP error:", err)
		return
	}
	defer resp.Body.Close()

	fmt.Println("[*] Task reported:", report["task_id"])
}

func cleanupAtomics() {
    fmt.Println("[*] Cleaning up atomics folder...")
    files, err := os.ReadDir(AtomicsDir)
    if err != nil {
        fmt.Println("[!] Error reading atomics directory:", err)
        return
    }

    for _, f := range files {
        if f.IsDir() && strings.HasPrefix(f.Name(), "T") {
            dirPath := filepath.Join(AtomicsDir, f.Name())
            if err := os.RemoveAll(dirPath); err != nil {
                fmt.Printf("[!] Failed to remove %s: %v\n", f.Name(), err)
            } else {
                fmt.Printf("[*] Removed technique folder: %s\n", f.Name())
            }
        }
    }

    // Clean ExternalPayloads folder (sibling to atomics)
    absAtomicsPath, _ := filepath.Abs(AtomicsDir)
    externalPayloadsPath := filepath.Join(filepath.Dir(absAtomicsPath), "ExternalPayloads")
    
    if _, err := os.Stat(externalPayloadsPath); err == nil {
        fmt.Println("[*] Cleaning ExternalPayloads folder:", externalPayloadsPath)
        
        // Remove all contents inside ExternalPayloads
        entries, err := os.ReadDir(externalPayloadsPath)
        if err == nil {
            for _, entry := range entries {
                entryPath := filepath.Join(externalPayloadsPath, entry.Name())
                if err := os.RemoveAll(entryPath); err != nil {
                    fmt.Printf("[!] Failed to remove %s: %v\n", entry.Name(), err)
                } else {
                    fmt.Printf("[*] Removed: %s\n", entry.Name())
                }
            }
        }
        
        fmt.Println("[*] ExternalPayloads cleanup completed")
    }

    fmt.Println("[*] Atomics cleanup completed")
}

func loadAtomicYaml(yamlPath string) (*AtomicTechnique, error) {
	data, err := ioutil.ReadFile(yamlPath)
	if err != nil {
		return nil, err
	}

	var atomicTech AtomicTechnique
	err = yaml.Unmarshal(data, &atomicTech)
	if err != nil {
		var rawData map[string]interface{}
		err2 := yaml.Unmarshal(data, &rawData)
		if err2 != nil {
			return nil, fmt.Errorf("failed to parse YAML: %v", err)
		}

		atomicTech = AtomicTechnique{}

		if attackTech, ok := rawData["attack_technique"].(string); ok {
			atomicTech.AttackTechnique = attackTech
		}

		if displayName, ok := rawData["display_name"].(string); ok {
			atomicTech.DisplayName = displayName
		}

		if testsData, ok := rawData["atomic_tests"].([]interface{}); ok {
			for _, testData := range testsData {
				if testMap, ok := testData.(map[string]interface{}); ok {
					test := parseAtomicTestFlexible(testMap)
					atomicTech.AtomicTests = append(atomicTech.AtomicTests, test)
				}
			}
		}
	}

	return &atomicTech, nil
}

func parseAtomicTestFlexible(testMap map[string]interface{}) AtomicTest {
	test := AtomicTest{
		InputArguments: make(map[string]InputArg),
		Dependencies:   []Dependency{},
	}

	if name, ok := testMap["name"].(string); ok {
		test.Name = name
	}

	if desc, ok := testMap["description"].(string); ok {
		test.Description = desc
	}

	if guid, ok := testMap["auto_generated_guid"].(string); ok {
		test.AutoGeneratedGuid = guid
	}

	if platforms, ok := testMap["supported_platforms"].([]interface{}); ok {
		for _, p := range platforms {
			if platform, ok := p.(string); ok {
				test.SupportedPlatforms = append(test.SupportedPlatforms, platform)
			}
		}
	}

	if inputArgs, ok := testMap["input_arguments"].(map[string]interface{}); ok {
		for key, val := range inputArgs {
			if argMap, ok := val.(map[string]interface{}); ok {
				arg := InputArg{}
				if desc, ok := argMap["description"].(string); ok {
					arg.Description = desc
				}
				if argType, ok := argMap["type"].(string); ok {
					arg.Type = argType
				}
				arg.Default = argMap["default"]
				test.InputArguments[key] = arg
			}
		}
	}

	if deps, ok := testMap["dependencies"].([]interface{}); ok {
		for _, depData := range deps {
			if depMap, ok := depData.(map[string]interface{}); ok {
				dep := Dependency{}
				if desc, ok := depMap["description"].(string); ok {
					dep.Description = desc
				}
				if prereq, ok := depMap["prereq_command"].(string); ok {
					dep.PrereqCommand = prereq
				}
				if getPrereq, ok := depMap["get_prereq_command"].(string); ok {
					dep.GetPrereqCommand = getPrereq
				}
				test.Dependencies = append(test.Dependencies, dep)
			}
		}
	}

	if executor, ok := testMap["executor"].(map[string]interface{}); ok {
		if name, ok := executor["name"].(string); ok {
			test.Executor.Name = name
		}
		if cmd, ok := executor["command"].(string); ok {
			test.Executor.Command = cmd
		}
		if cleanup, ok := executor["cleanup_command"].(string); ok {
			test.Executor.CleanupCommand = cleanup
		}
		if elevReq, ok := executor["elevation_required"].(bool); ok {
			test.Executor.ElevationRequired = elevReq
		}
	}

	return test
}

func isPlatformSupported(platforms []string) bool {
	currentOS := runtime.GOOS
	for _, platform := range platforms {
		platform = strings.ToLower(platform)
		if strings.Contains(platform, currentOS) ||
			(currentOS == "windows" && platform == "windows") ||
			(currentOS == "linux" && platform == "linux") ||
			(currentOS == "darwin" && platform == "macos") {
			return true
		}
	}
	return false
}
func isElevated() bool {
	if runtime.GOOS == "windows" {
		// Try to open a file that requires admin access
		cmd := exec.Command("powershell.exe", "-NoProfile", "-Command",
			"([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)")
		output, err := cmd.Output()
		if err != nil {
			return false
		}
		return strings.TrimSpace(strings.ToLower(string(output))) == "true"
	}
	// Linux/Mac - check if running as root
	return os.Getuid() == 0
}
func replaceVariables(command string, args map[string]string) string {
    result := command
    for key, value := range args {
        result = strings.ReplaceAll(result, fmt.Sprintf("#{%s}", key), value)
        result = strings.ReplaceAll(result, fmt.Sprintf("$%s", key), value)
    }
    
    // FIX: Also replace bare PathToAtomicsFolder
    if atomicsPath, ok := args["PathToAtomicsFolder"]; ok {
        result = strings.ReplaceAll(result, "PathToAtomicsFolder", atomicsPath)
    }
	
    // FIX 4: Resolve paths containing .. on Windows (preserve newlines)
    if strings.Contains(result, "..") && runtime.GOOS == "windows" {
        lines := strings.Split(result, "\n")
        for i, line := range lines {
            words := strings.Fields(line)
            for j, word := range words {
                if len(word) >= 3 && word[1] == ':' && strings.Contains(word, "..") {
                    cleanWord := strings.Trim(word, "\"'")
                    if resolved, err := filepath.Abs(cleanWord); err == nil {
                        normalized := filepath.Clean(resolved)
                        words[j] = strings.Replace(word, cleanWord, normalized, 1)
                    }
                }
            }
            lines[i] = strings.Join(words, " ")
        }
        result = strings.Join(lines, "\n")
    }
	
    return result
}

func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

func toString(v interface{}) string {
	if v == nil {
		return ""
	}
	s, ok := v.(string)
	if ok {
		return s
	}
	return fmt.Sprintf("%v", v)
}
// cleanupOrphanedCmd kills any orphaned cmd.exe processes that may hang
func cleanupOrphanedCmd() {
	if runtime.GOOS != "windows" {
		return
	}
	exec.Command("powershell.exe", "-NoProfile", "-WindowStyle", "Hidden", "-Command",
		"Get-Process cmd -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowTitle -eq '' } | Stop-Process -Force -ErrorAction SilentlyContinue").Run()
}
func unzip(src, dest string) error {
	r, err := zip.OpenReader(src)
	if err != nil {
		return err
	}
	defer r.Close()

	for _, f := range r.File {
		path := filepath.Join(dest, f.Name)

		if f.FileInfo().IsDir() {
			os.MkdirAll(path, f.Mode())
			continue
		}

		os.MkdirAll(filepath.Dir(path), 0755)

		outFile, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
		if err != nil {
			return err
		}

		rc, err := f.Open()
		if err != nil {
			outFile.Close()
			return err
		}

		_, err = io.Copy(outFile, rc)
		rc.Close()
		outFile.Close()

		if err != nil {
			return err
		}
	}

	return nil
}
